---
- "1": "other"
- "2": "ok"
- "3": "Failed"
- "4": "Unconfigured"
- "5": "Recovering"
- "6": "Ready Rebuild"
- "7": "Rebuilding"
- "8": "Wrong Drive"
- "9": "Bad Connect"
- "10": "Overheating"
- "11": "Shutdown"
- "12": "Expanding"
- "13": "Not Available"
- "14": "Queued For Expansion"
- "15": "Multi-path Access Degraded"
- "16": "Erasing"
- "17": "Predictive Spare Rebuild Ready"
- "18": "Rapid Parity Initialization In Progress"
- "19": "Rapid Parity Initialization Pending"
- "20": "No Access – Encrypted with No Controller Key"
- "21": "Unencrypted to Encrypted Transformation in Progress"
- "22": "New Logical Drive Key Rekey in Progress"
- "23": "No Access – Encrypted with Controller Encryption Not Enabled"
- "24": "Unencrypted To Encrypted Transformation Not Started"
- "25": "New Logical Drive Key Rekey Request Received"
