---
- "1": "other"
- "2": "notPresent"
- "3": "present"
- "4": "good"
- "5": "add"
- "6": "upgrade"
- "7": "missing"
- "8": "doesNotMatch"
- "9": "notSupported"
- "10": "badConfig"
- "11": "degraded"
- "12": "spare"
- "13": "partial"
