{
 "title": "Audit Config Summary Per Runtime",
 "tags": [ "audit" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "table", "label": "Table", "query": "show tables;" },
   { "name": "data", "label": "Data", "query": "current,history" },
   {
    "name": "runtime",
    "label": "RunTime",
    "query": "select runtime from [[table]]_[[data]]"
   },
   {
    "name": "test_name",
    "label": "Test Name",
    "query": "select test_name from [[table]]_[[data]] where runtime=\"$runtime\""
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "select hostname from [[table]]_[[data]] where runtime=\"$runtime\""
   },
   {
    "name": "address",
    "label": "Address",
    "query": "select address from [[table]]_[[data]] where hostname in ($hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Snapshot time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(pre_time, \"%Y-%m-%d %H:%i:%S\") AS Pre_time \nFROM [[table]]_[[data]]\nWHERE runtime=\"$runtime\""
    }
   ]
  },
  {
   "title": "Test Result Summary",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT  test_name, \r\n        SUM(if(Rate = 1, 1, 0)) AS HOST_PASSED,\r\n        SUM(if(Rate < 1, 1, 0)) AS HOST_FAILED\r\nFROM  \r\n(\r\n    SELECT \r\n      hostname, \r\n      address, \r\n      test_name,\r\n      SUM(if(result = 0, 1, 0)) as PASSED_items,\r\n      SUM(if(result = 1, 1, 0)) as FAILED_items,\r\n      SUM(if(result = 2, 1, 0)) as SKIPPED_items,\r\n      IF(SUM(if(result = 0, 1, 0)) + SUM(if(result = 1, 1, 0)) = 0, null, (SUM(if(result = 0, 1, 0))/( SUM(if(result = 0, 1, 0)) + SUM(if(result = 1, 1, 0)) ) )) as Rate\r\n\r\n    FROM [[table]]_history\r\n    WHERE hostname in ($hostname) \r\n        and address in ($address) \r\n        and test_name in ($test_name) \r\n        and runtime=\"$runtime\"\r\n        and UNIX_TIMESTAMP(lastUpdated) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\r\n    GROUP BY hostname, test_name\r\n) \r\nas PASSED_clause\r\nGROUP BY test_name"
    }
   ]
  },
  {
   "title": "Test Result Overview",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE\r\n    WHEN INSTR(\"[[table]]\", \"snapcheck\") THEN \"snapcheck\"\r\n    WHEN INSTR(\"[[table]]\", \"compare\") THEN \"compare\"\r\n  END\r\n  as audit_type,\r\n  test_name,\r\n  hostname, \r\n  address, \r\n  SUM(if(result = 0, 1, 0)) as PASSED_items,\r\n  SUM(if(result = 1, 1, 0)) as FAILED_items,\r\n  SUM(if(result = 2, 1, 0)) as SKIPPED_items,\r\n  IF(SUM(if(result = 0, 1, 0)) + SUM(if(result = 1, 1, 0)) = 0, null, (SUM(if(result = 0, 1, 0))/( SUM(if(result = 0, 1, 0)) + SUM(if(result = 1, 1, 0)) ) )) as Rate,\r\n  runtime as Runtime\r\nFROM [[table]]_history\r\nWHERE hostname in ($hostname) \r\n    and address in ($address) \r\n    and test_name in ($test_name) \r\n    and runtime=\"$runtime\"\r\n    and UNIX_TIMESTAMP(lastUpdated) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\r\nGROUP BY hostname, test_name\r\n"
    }
   ]
  }
 ]
}