beats_version: "{{ version }}"
use_repository: true
beats_add_repository: false
version_lock: true
start_service: true
restart_on_change: true
#output_conf : {
#  "elasticsearch": {
#    hosts: "[{% for host in groups['elastic'] %}\"{{hostvars[host].ansible_host}}:{{ http_port }}\"{% if not loop.last %}, {% endif %}{% endfor %}]",
#     index: "metricbeat-%{+yyyy.MM}",
#     username: "elastic",
#     password: "juniper@123",
#     ssl.verification_mode: "none",
#     protocol: "https"
#     #api_key: id:api_key
#  }
#}
output_conf: {
  logstash: {
    hosts: "[{% for host in groups['logstash'] %}\"{{hostvars[host].ansible_host}}:{{ beats.logstash.listen_port.metricbeat }}\"{% if not loop.last %}, {% endif %}{% endfor %}]",
    loadbalance: true
  }
}
logging_conf: {
  files: {
    rotateeverybytes: 10485760
  },
  level: "warning"
}
default_ilm_policy: "{{ playbook_dir }}/roles/elk_beat/files/ilm_metricbeat.json"
beat: metricbeat

beat_conf:
  setup:
    ilm:
      policy_file: "/etc/metricbeat/policies/default_ilm.json"
      overwrite: false
      enabled: auto
      rollover_alias: "metricbeat"
      pattern: "{now/d}-000001"
    metricbeat.modules:
      module: system

  metricbeat.config.modules:
    path: "${path.config}/modules.d/*.yml"
    reload.enabled: true
    reload.period: "{{ beats.system_reload_period }}"
  logging.metrics.enabled: false

  setup.template.settings:
    index.number_of_shards: 3
    index.codec: best_compression
    #"_source.enabled": false

  setup.template.name: "metricbeat"
  setup.template.pattern: "metricbeat-*"
#  setup.template.fields: "custom_fields.yml"
  setup.template.overwrite: false

  setup.kibana:
    host: localhost:5601
    #"space.id":

  processors:
    - add_host_metadata:
        netinfo.enabled: true
        cache.ttl: 5m
    - add_fields:
        fields:
          group: "{{ app_group }}"
    #"add_cloud_metadata": "~"
    #"- add_docker_metadata": "~"
    #"- add_kubernetes_metadata": "~"
