---
- "0": "KERNEL"
- "1": "USER"
- "2": "MAIL"
- "3": "DAEMON"
- "4": "AUTHORIZATION"
- "5": "SYSLOG"
- "6": "PRINTER"
- "7": "NEWS"
- "8": "UUCP"
- "9": "CLOCK"
- "10": "AUTHORIZATION-PRIVATE"
- "11": "FTP"
- "12": "NTP"
- "13": "SECURITY"
- "14": "CONSOLE"
- "16": "LOCAL0"
- "17": "DFC"
- "18": "LOCAL2"
- "19": "FIREWALL"
- "20": "PFE"
- "21": "CONFLICT-LOG"
- "22": "CHANGE-LOG"
- "23": "INTERACTIVE-COMMANDS"
