# Wrote by Hoang Anh Tu
---
- name: IPTABLES [Step 01] - Stop Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

- name: IPTABLES [Step 02] - Install Iptables
  yum:
    name: "{{ item.service }}"
    state: latest
  with_items:
    - { service: "iptables" }
    - { service: "iptables-services" }

- name: IPTABLES [Step 02] - Add ELK Ports to Firewall
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertafter: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
    state: present
    backup: yes
    marker: '# {mark} ANSIBLE MANAGED BLOCK - ELK'
    content: |
      {% for host in groups['elastic'] %}
      {% if loop.first %}
      # ES-INTERNAL
      {% endif %}
      {% if hostvars[host].ansible_host != ansible_host %}
      -A INPUT -s {{hostvars[host].IP}} -p tcp -m state --state NEW -m tcp --dport {{ transport_port }} -m comment --comment "ES TRANSPORT Port" -j ACCEPT
      {% endif %}
      {% endfor %}
      {% if 'elastic' in group_names %}
      # ES-EXTERNAL
      -A INPUT -p tcp -m state --state NEW -m tcp --dport {{ http_port }} -m comment --comment "ES HTTP/External Port" -j ACCEPT
      {% endif %}
      {% if 'kibana' in group_names %}
      # KIBANA
      -A INPUT -p tcp -m state --state NEW -m tcp --dport {{ kibana_port }} -m comment --comment "Kibana Port" -j ACCEPT
      # LOGSTASH 
      {% for service, port in beats.logstash.listen_port.items() %}
      -A INPUT -p tcp -m state --state NEW -m tcp --dport {{ port }} -m comment --comment "{{ service }} Port" -j ACCEPT
      {% endfor %}
      # HTTP
      -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -m comment --comment "HTTP Port" -j ACCEPT
      {% endif %}


- name: IPTABLES [Step 03] - Start Iptables
  service:
    name: iptables
    state: restarted
    enabled: yes
