{
 "title": "01 - AAA - Accouting",
 "tags": [ "AAA" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Data Received",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "metricset.name: \"json\" AND event.dataset: \"http.accounting\" AND (host.name: \"[[hostname]]\" OR not host.name:*)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  float: right;\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/grafana/d/menu/menu?orgId=1', '_self')\"><span>BACK TO MENU</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overview Informations (SUM of Selected Hosts) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Current - Starts",
   "type": "stat",
   "description": "Sum Of Current Starts Transaction [[hostname]]",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_start_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Peak - Starts",
   "type": "stat",
   "description": "Sum Of Peak Starts Transaction [[hostname]]",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_start_peak_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total - Starts Transaction",
   "type": "stat",
   "description": "Sum Of Total Starts Transaction [[hostname]]",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.start",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Transactions (Starts + Stops) ",
   "type": "stat",
   "description": "Sum Total Transaction (Starts + Stops)  of [[hostname]]",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.start",
       "id": "1",
       "type": "avg"
      },
      {
       "field": "http.accounting.data.accounting.stop",
       "id": "4",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current - Stops",
   "type": "stat",
   "description": "Sum Of Current Stops Transaction [[hostname]]",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_stop_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Peak - Stops",
   "type": "stat",
   "description": "Sum Of Peak Stops Transaction [[hostname]]",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_stop_peak_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Stops Transaction",
   "type": "stat",
   "description": "Sum Total Transaction (Stops) [[hostname]]",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.stop",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Historical Accouting Informations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Starts Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_start_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Stop Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_stop_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accounting Statistics per SBR Node (Runtime)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "[[hostname]]",
   "type": "table",
   "gridPos": { "h": 24, "w": 6, "x": 0, "y": 22 },
   "repeat": "hostname",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[[hostname]]",
   "type": "table",
   "gridPos": { "h": 24, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[[hostname]]",
   "type": "table",
   "gridPos": { "h": 24, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[[hostname]]",
   "type": "table",
   "gridPos": { "h": 24, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[[hostname]]",
   "type": "table",
   "gridPos": { "h": 24, "w": 6, "x": 0, "y": 46 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[[hostname]]",
   "type": "table",
   "gridPos": { "h": 24, "w": 6, "x": 6, "y": 46 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "metricset.name: json AND host.name: [[hostname]] ",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}