{
 "title": "03 - AAA - Subscriber's User Overview",
 "tags": [ "AAA" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter_user", "label": "Filter User" },
   { "name": "limit", "label": "Limit", "query": "100,1000,10000,100000" },
   {
    "name": "bras",
    "label": "BRAS",
    "query": "select distinct bras from logininfo where username REGEXP \"$filter_user\""
   },
   {
    "name": "profile",
    "label": "Profile",
    "query": "select distinct(groupname) from usergroup;"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  float: right;\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/grafana/d/menu/menu?orgId=1', '_self')\"><span>BACK TO MENU</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Subscriber User Overview Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "select count(distinct(username)) from usergroup;"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT COUNT(distinct(username)) \nFROM logininfo\nWHERE status =1"
    }
   ]
  },
  {
   "title": "Subcribers Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT \n  t2.groupname as PolicyName,\n  IFNULL(count(t1.username), 0) as Count\nFROM logininfo t1\nJOIN usergroup t2 ON t1.username = t2.username and t2.groupname in ($profile)\ngroup by t2.groupname\nlimit $limit",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User Information",
   "type": "briangann-datatable-panel",
   "description": "Clickable column: UserName, Profile ",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT \r\n  t1.logindate as LoginDate,\r\n  t1.username as UserName,\r\n  t2.groupname as Profile,\r\n  t1.acctsessionid as SessionID,\r\n  t4.mac as MAC,\r\n  t1.bras as BRAS,\r\n  t1.status as Status,\r\n  t1.s_active as Active,\r\n  t1.s_password as Corect_Passwd,\r\n  #t1.password as Passwd,\r\n  t1.nasport as BrasPort,\r\n  t1.s_nasport,\r\n  t3.value as Static_IP\r\n\r\nFROM logininfo t1\r\nLEFT JOIN usergroup t2 ON t1.username = t2.username \r\nLEFT JOIN radreply t3 ON t1.username = t3.username \r\nLEFT JOIN usercheck t4 ON t1.username = t4.username \r\n\r\nWHERE t1.username REGEXP '($filter_user)' \r\nLIMIT $limit",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}