{
 "title": "07 - AAA - Juniper Session Information",
 "tags": [ "AAA" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "user_filter", "label": "User Filter" },
   {
    "name": "bras",
    "label": "BRAS",
    "query": "select Sbr_NasName from Sbr_CurrentSessions limit 120"
   },
   {
    "name": "field",
    "label": "Display Field",
    "query": "SELECT `COLUMN_NAME` \nFROM `INFORMATION_SCHEMA`.`COLUMNS` \nWHERE `TABLE_SCHEMA`='SteelBeltedRadius' \n    AND `TABLE_NAME`='Sbr_CurrentSessions';"
   },
   { "name": "limit", "label": "Limit Query", "query": "10,100,1000,10000" },
   { "name": "client_port", "label": "Client Port" }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  float: right;\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/grafana/d/menu/menu?orgId=1', '_self')\"><span>BACK TO MENU</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Concurrent Sesion on BRAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Concurrent session per Bras",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "select Sbr_NasName,count(Sbr_UserName) as session_number from Sbr_CurrentSessions group by Sbr_NasName order by count(Sbr_UserName) desc limit ${limit} ;",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Session History ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sql.metrics.string.brasname",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.usercount",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.name: query sql.metrics.string.brasname = \"[[bras]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Concurrent Session Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Concurrent Session Detail",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "rawSql": "select conv(hex(Sbr_UniqueSessionId),16,10) as Sbr_UniqueSessionId,INET_NTOA(Sbr_Ipv4Address) as Sbr_Ipv4Address,Sbr_SessionState,${field:csv} from Sbr_CurrentSessions limit $limit",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}