{
 "title": "09 - AAA - Authentication Log",
 "tags": [ "AAA" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "logtype", "label": "logtype", "query": "radius-auth-log" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\", \"query\":\"log.type:[[logtype]] AND service.type:radius\"}"
   },
   {
    "name": "bras_name",
    "label": "BRAS Name",
    "query": "{\"find\": \"terms\", \"field\": \"ras_client\", \"query\":\"log.type:[[logtype]] AND host.name:[[hostname]]\"}"
   },
   {
    "name": "auth_status",
    "label": "Authentication Status",
    "query": "{\"find\": \"terms\", \"field\": \"acc_rej\", \"query\":\"log.type:[[logtype]] AND host.name:[[hostname]] AND ras_client:[[bras_name]]\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Data Received",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "log.type:[[logtype]] AND service.type:\"radius\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  float: right;\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/grafana/d/menu/menu?orgId=1', '_self')\"><span>BACK TO MENU</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AAA Authentication Log Overview Informations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Number of Authentication Request",
   "type": "stat",
   "description": "Number of Authentication Request",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log.type:[[logtype]] AND host.name:[[hostname]] AND ras_client:[[bras_name]] AND acc_rej:[[auth_status]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of BRAS",
   "type": "stat",
   "description": "Number of BRAS sent Authentication Request",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "host.name", "id": "1", "type": "cardinality" }
     ],
     "query": "log.type:[[logtype]] AND host.name:[[hostname]] AND ras_client:[[bras_name]] AND acc_rej:[[auth_status]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Summary Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "7",
       "type": "count"
      },
      { "field": "ras_client", "id": "8", "type": "cardinality" },
      { "field": "nas_port", "id": "9", "type": "cardinality" },
      { "field": "user_name", "id": "10", "type": "cardinality" }
     ],
     "query": "log.type:[[logtype]] AND host.name:[[hostname]] AND ras_client:[[bras_name]] AND acc_rej:[[auth_status]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Nas Port",
   "type": "stat",
   "description": "Number of Nas Port",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "nas_port", "id": "1", "type": "cardinality" }
     ],
     "query": "log.type:[[logtype]] AND host.name:[[hostname]] AND ras_client:[[bras_name]] AND acc_rej:[[auth_status]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Clients",
   "type": "stat",
   "description": "Number of Authenticated Clients",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "user_name", "id": "1", "type": "cardinality" }
     ],
     "query": "host.name:[[hostname]] AND ras_client:[[bras_name]] AND acc_rej:[[auth_status]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs BRAS Over Time - Authentication Status: [[auth_status]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ras_client",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log.type:[[logtype]] AND host.name:[[hostname]] AND ras_client:[[bras_name]] AND acc_rej:[[auth_status]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Authentication Logs by BRAS - Authentication Status: [[auth_status]]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ras_client",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log.type:[[logtype]] AND host.name:[[hostname]] AND ras_client:[[bras_name]] AND acc_rej:[[auth_status]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Authentication Logs by Hostname - Authentication Status: [[auth_status]]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log.type:[[logtype]] AND host.name:[[hostname]] AND ras_client:[[bras_name]] AND acc_rej:[[auth_status]]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Log Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": " Authentication Log - Authentication Status: [[auth_status]]",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 44, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1000" }, "type": "raw_data" }
     ],
     "query": "log.type:[[logtype]] AND host.name:[[hostname]] AND ras_client:[[bras_name]] AND acc_rej:[[auth_status]]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}