- name: Install build dependencies
  homebrew:
    name: "{{ item }}"
  with_flattened:
  - "{{ pyenv_darwin_build_dependencies }}"
  - "{{ pyenv_darwin_additional_build_dependencies }}"
  when: pyenv_is_dependencies_installed
