# hoanganht1k27
---
- name: IPTABLES [Step 01] - Stop Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true

- name: IPTABLES [Step 02] - Install Iptables
  yum:
    name: iptables
    state: present
  when: ansible_os_family == "RedHat"

- name: IPTABLES [Step 02] - Install Iptables
  apt:
    name: iptables
    state: present
  when: ansible_os_family == "Debian"

- name: IPTABLES [Step 03]-[Single] - Add node exporter port to config file
  lineinfile:
    dest: /etc/sysconfig/iptables
    insertbefore: '-A INPUT -j REJECT --reject-with icmp-host-prohibited'
    line: '{{ item }}'
    state: present
  with_items:
    - "# NODE EXPORTER #"
    - "-A INPUT -p tcp -m state --state NEW -m tcp --dport {{ node_exporter_port }} -m comment --comment \"Node exporter port\" -j ACCEPT"
  when: ansible_os_family == "RedHat"
  ignore_errors: true

#- name: IPTABLES [Step 03]-[Single] - Add node exporter port to config file
#  lineinfile:
#    dest: /etc/iptables/rules.v4
#    insertbefore: '-P INPUT -j REJECT'
#    line: '{{ item }}'
#    state: present
#  with_items:
#    - "# NODE EXPORTER #"
#    - "-A INPUT -p tcp -m state --state NEW -m tcp --dport {{ node_exporter_port }} -m comment --comment \"Node exporter port\" -j ACCEPT"
#  when: ansible_os_family == "Debian"
#  notify:
#    - Restart Iptables
- name: IPTABLES [Step 04] - Add node exporter port to Firewall
  iptables:
    action: "insert"
    chain: INPUT
    protocol: tcp
    destination_port: "{{ node_exporter_port | int}}"
    ctstate: NEW
    comment: "Node exporter port"
    jump: ACCEPT
