- name: Kill existing process
  shell: |
    pid=$(lsof -t -i :{{ node_exporter_port }});
    if [ -n "${pid}" ]; then
      echo "Killing process ${pid}";
      kill ${pid};
    fi;
  ignore_errors: true
- name: Run node_exporter
  shell: |
    cd {{ tar_gz_folder }}/node_exporter-1.5.0.linux-amd64
    nohup ./node_exporter &
