{
 "title": "02 - Service - MariaDB Information",
 "tags": [ "Metric" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Groups",
    "query": "{\"find\": \"terms\", \"field\": \"fields.group\", \"query\": \"\"}"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\", \"query\": \"event.dataset: mysql.galera_status AND fields.group:[[group]]\"}"
   }
  ]
 },
 "panels": [
  { "title": "MariaDB Status Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL / MariaDB Table Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "6", "type": "logs" }
     ],
     "query": "event.dataset:mysql.galera_status AND host.name:[[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rate of Statements (Request per 30 Sec)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Rate of Questions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Request per 30 Sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mysql.status.questions",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "1",
       "hide": false,
       "id": "4",
       "pipelineAgg": "1",
       "settings": { "unit": "30s" },
       "type": "derivative"
      }
     ],
     "query": "host.name: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rate of Select Statements",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Request per 30 Sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mysql.status.command.select",
       "hide": true,
       "id": "1",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "hide": false,
       "id": "4",
       "pipelineAgg": "1",
       "settings": { "unit": "30s" },
       "type": "derivative"
      }
     ],
     "query": "host.name: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rate of Insert Statements",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Request per 30 Sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mysql.status.command.insert",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "1",
       "hide": false,
       "id": "4",
       "pipelineAgg": "1",
       "settings": { "unit": "30s" },
       "type": "derivative"
      }
     ],
     "query": "host.name: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rate of Update Statements",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Request per 30 Sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mysql.status.command.update",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "1",
       "hide": false,
       "id": "4",
       "pipelineAgg": "1",
       "settings": { "unit": "30s" },
       "type": "derivative"
      }
     ],
     "query": "host.name: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rate of Delete Statements",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "Request per 30 Sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mysql.status.command.delete",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "1",
       "hide": false,
       "id": "4",
       "pipelineAgg": "1",
       "settings": { "unit": "30s" },
       "type": "derivative"
      }
     ],
     "query": "host.name: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Slow Logs Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Slow Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "mysql.slowlog.query",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Unique Number of Slow Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "mysql.slowlog.query",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "mysql.slowlog.query", "id": "1", "type": "cardinality" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Slow Log breakdown",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "50" }, "type": "raw_data" }
       ],
       "query": "mysql.slowlog.query: * AND host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Logs Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Error Logs",
     "type": "stat",
     "gridPos": { "h": 15, "w": 5, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "log.level",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "event.module: mysql AND host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Error Logs",
     "type": "table",
     "gridPos": { "h": 15, "w": 19, "x": 5, "y": 39 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "event.module: mysql AND fileset.name: error AND host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Commands Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commands Operations Of [[hostname]] Node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Select",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.command.select",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "7",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Insert",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.command.insert",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "7",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Update",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.command.update",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "7",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Delete",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.command.delete",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "7",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads Connected",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.threads.connected", "id": "1", "type": "max" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Threads Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.threads.running", "id": "1", "type": "max" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pool Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Pool Utilization ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.innodb.buffer_pool.pages.free",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "mysql.status.innodb.buffer_pool.pages.total",
         "hide": true,
         "id": "8",
         "settings": {},
         "type": "max"
        },
        {
         "id": "9",
         "pipelineVariables": [
          { "name": "free", "pipelineAgg": "1" },
          { "name": "total", "pipelineAgg": "8" }
         ],
         "settings": {
          "script": "params.total != null && params.total > 0 ? (params.total - params.free)/params.total : null"
         },
         "type": "bucket_script"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Buffer Pool Efficiency (lower is better)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.innodb.buffer_pool.pool.reads",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "mysql.status.innodb.buffer_pool.read.requests",
         "hide": true,
         "id": "8",
         "settings": {},
         "type": "max"
        },
        {
         "id": "9",
         "pipelineVariables": [
          { "name": "pool_reads", "pipelineAgg": "1" },
          { "name": "pool_read_requests", "pipelineAgg": "8" }
         ],
         "settings": {
          "script": "params.pool_read_requests != null && params.pool_read_requests > 0 ? (params.pool_reads/params.pool_read_requests) * 100: null"
         },
         "type": "bucket_script"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "group",
   "collapsed": true,
   "panels": [
    {
     "title": "[[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Connection Rate",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.connections",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Connected ",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.threads.connected",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Max Used Connections ",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.max_used_connections",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "[[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Connection Rate",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.connections",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Connected ",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.threads.connected",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Max Used Connections ",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.max_used_connections",
         "id": "1",
         "type": "max"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Aborted Connections Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "group",
   "collapsed": true,
   "panels": [
    {
     "title": "[[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Aborted Connections",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.aborted.clients",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Failed Attempts to Connect ",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.aborted.connects",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "[[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Aborted Connections",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.aborted.clients",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Failed Attempts to Connect ",
       "bucketAggs": [
        {
         "field": "host.name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.aborted.connects",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Networks Traffics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Received Bytes",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.bytes.received",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Sent bytes",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.bytes.sent",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Traffic of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Received Bytes",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.bytes.received",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Sent bytes",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.bytes.sent",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Open Tables Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Hits",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.cache.table.open_cache.hits",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Misses",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.cache.table.open_cache.misses",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Overflows",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.cache.table.open_cache.overflows",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Hits",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.cache.table.open_cache.hits",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Misses",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.cache.table.open_cache.misses",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Overflows",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "mysql.status.cache.table.open_cache.overflows",
         "hide": true,
         "id": "1",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "8",
         "pipelineAgg": "1",
         "settings": { "unit": "30s" },
         "type": "derivative"
        }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Open tables, files, streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Open Tables Cache of [[hostname]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Open Tables",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.tables", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Files",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.files", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Open Streams",
       "bucketAggs": [
        { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "mysql.status.open.streams", "id": "1", "type": "avg" }
       ],
       "query": "host.name: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}