{
 "title": "03 - Service - Api Gateway - SQL Proxy",
 "tags": [ "Metric" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "{\"find\": \"terms\", \"field\": \"agent.hostname\", \"query\": \"fields.group:AAA\"}"
   },
   {
    "name": "hostgroup",
    "label": "Proxysql-Hostgroup",
    "query": "{\"find\": \"terms\", \"field\": \"sql.metrics.numeric.hostgroup\", \"query\": \"agent.hostname: [[host]] AND fields.group:AAA and sql.metrics.numeric.hostgroup:*\"}"
   },
   {
    "name": "host_backend",
    "label": "Proxysql-Backend-Host",
    "query": "{\"find\": \"terms\", \"field\": \"sql.metrics.string.host\", \"query\": \"agent.hostname: [[host]] AND fields.group:AAA and sql.metrics.numeric.hostgroup:[[hostgroup]]\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Data Received",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "service.name: proxysql AND (agent.hostname: [[host]] OR not agent.hostname:*)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  float: right;\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/grafana/d/menu/menu?orgId=1', '_self')\"><span>BACK TO MENU</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "PROXYSQL - Backend Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Backend MariaDB Status",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "150" }, "type": "raw_data" }
     ],
     "query": "agent.hostname: [[host]] AND sql.metrics.numeric.status:* AND sql.metrics.numeric.hostgroup:[[hostgroup]] AND sql.metrics.string.host:[[host_backend]]",
     "rawSql": "SELECT hostgroup, srv_host as Host, \nCASE \nwhen status = 'ONLINE' then 0\nwhen status = 'SHUNNED' then 1\nwhen status = 'OFFLINE_SOFT' then 2\nwhen status = 'OFFLINE_HARD' then 3\nelse 1\nEND as status, ConnUsed, ConnFree, ConnOK, ConnERR, Bytes_data_sent, Bytes_data_recv, Latency_us\nFROM stats_mysql_connection_pool where srv_host in ($host) ORDER BY Bytes_data_recv desc, hostgroup asc, srv_host asc;",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "PROXYSQL - User Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Current User Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "100" }, "type": "raw_data" }
     ],
     "query": "agent.hostname: [[host]] AND sql.metrics.string.username:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Frontend Connections",
   "type": "graph",
   "description": "The number of connections currently used by user",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sql.metrics.string.username",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.frontend_connections",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "agent.hostname: [[host]]",
     "rawSql": " select username, \n frontend_connections as front_connection, \n frontend_max_connections as front_max_connection from stats_mysql_users;",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Frontend Max Connections",
   "type": "graph",
   "description": "The maximum number of connections this user is allowed to use, as configured in the mysql_users table in ProxySQL",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sql.metrics.string.username",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.frontend_max_connections",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "agent.hostname: [[host]]",
     "rawSql": " select username, \n frontend_connections as front_connection, \n frontend_max_connections as front_max_connection from stats_mysql_users;",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data and Rate from Sent/Received Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Frontends Data Received (all time)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.queries_frontends_bytes_recv",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "agent.hostname: [[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Frontends Data Rate Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.queries_frontends_bytes_recv",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
     ],
     "query": "agent.hostname: [[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Frontends Data Sent (all time)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.queries_frontends_bytes_sent",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "agent.hostname: [[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Frontends Data Rate Sent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.queries_frontends_bytes_sent",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
     ],
     "query": "agent.hostname: [[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Backends Data Received (all time)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.queries_backends_bytes_recv",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "agent.hostname: [[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Backends Data Rate Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.queries_backends_bytes_recv",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
     ],
     "query": "agent.hostname: [[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Backends Data Sent (all time)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.queries_backends_bytes_sent",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "agent.hostname: [[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Backends Data Rate Sent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sql.metrics.numeric.queries_backends_bytes_sent",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
     ],
     "query": "agent.hostname: [[host]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PROXYSQL - Commands Informations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Summary Queries' Informations",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "200" }, "type": "raw_data" }
     ],
     "query": "agent.hostname: [[host]] AND sql.metrics.string.first_time:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PROXYSQL - Attribute Informations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "[[host]] - Uptime",
     "type": "stat",
     "description": "The total uptime of ProxySQL",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 59 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
       ],
       "query": "agent.hostname: [[host]] AND sql.metrics.numeric.proxysql_uptime:*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "[[host]] - Attribute Informations ",
     "type": "table",
     "description": "Each row represents a global statistic at the proxy level related to MySQL including:\n\nKey Memory Usage\nGlobal Connections\nConnection Pooling\nSQL Statements",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 62 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
       ],
       "query": "agent.hostname: [[host]] AND sql.metrics.numeric.proxysql_uptime:*",
       "rawSql": "select * from stats_mysql_global where Variable_Name in \n('Active_Transactions',\n'Client_Connections_aborted',\n'Client_Connections_connected',\n'Client_Connections_created',\n'Server_Connections_aborted',\n'Server_Connections_connected',\n'Server_Connections_created',\n'Questions',\n'Slow_queries',\n'max_connect_timeouts',\n'Access_Denied_Wrong_Password',\n'Access_Denied_Max_Connections',\n'Access_Denied_Max_User_Connections',\n'ConnPool_memory_bytes'\n);",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "PROXYSQL - Error Commands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "PROXYSQL - Error Commands",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "rawSql": "select * from stats_mysql_errors where hostname in ($host);",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}