---

### ------------------------------------------------------
### show route <destination>
### ------------------------------------------------------

RouteTable:
  rpc: get-route-information
  args_key: 
    - destination
    - hidden
  args:
    extensive: True
    hidden: False
  item: route-table/rt 
  key: rt-destination
  view: RouteTableView

RouteTableView:
  groups:
    entry: rt-entry
  fields_entry:
    # fields taken from the group 'entry'
    protocol: protocol-name
    via: nh/via | nh/nh-local-interface
    age: { age/@seconds : int }
    nexthop: nh/to
    as_path: as-path
    community: communities/community
    preference: preference | local-preference
  fields:
    rt_destination: rt-destination
    rt_prefix_length: rt-prefix-length

### ------------------------------------------------------
### show route summary
### ------------------------------------------------------

RouteSummaryTable:
  rpc: get-route-summary-information
  item: route-table
  key: table-name
  view: RouteSummaryView

RouteSummaryView:
  fields:
    table_name: table-name
    dests: { destination-count : int }
    total: { total-route-count : int }
    active: { active-route-count : int }
    holddown: { holddown-route-count : int }
    hidden: { hidden-route-count : int }
    protocols: _rspTable 

_rspTable:
  item: protocols
  key: protocol-name
  view: _rspView

_rspView:
  fields:
    protocol_name: protocol-name
    count: { protocol-route-count: int }
    active: { active-route-count : int }
