{
 "title": "FPC graph",
 "tags": [ "detail_graph" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "SHOW datasources;" },
   {
    "name": "hostgroup",
    "label": "Hostgroup",
    "query": "SELECT hostgroups.name FROM ${datasource:csv};"
   },
   {
    "name": "device_type",
    "label": "Device Type",
    "query": "SELECT hosts.vars.device_type FROM ${datasource:csv};"
   },
   { "name": "hoststate", "label": "Hoststate", "query": "show hoststate;" },
   {
    "name": "hostname",
    "label": "Device name",
    "query": "SELECT hosts.display_name FROM ${datasource:csv} WHERE state ~ (${hoststate:pipe}) AND groups ~ (${hostgroup:pipe}) AND vars.device_type = ${device_type:pipe};"
   },
   {
    "name": "address",
    "label": "IP address",
    "query": "SHOW TAG VALUES from hostalive  WITH KEY = \"address\" where device_type =~ /$device_type/  and hostname =~ /$hostname/ "
   },
   {
    "name": "FPC_No",
    "label": "FPC Number",
    "query": "show tag values with key = \"service\" where hostname =~ /$hostname/ ;"
   },
   { "name": "sampling", "label": "Sampling Interval", "query": "1m,2m,3m,4m,5m,6m,7m,8m,9m,10m" },
   {
    "name": "rp",
    "query": "select rp from forever.rp_config where  ($__to - $__from > \"start\") and ($__to - $__from <= \"end\")"
   }
  ]
 },
 "panels": [
  { "title": "$hostname - $address", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "CPU LOAD",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Load  - $tag_service",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Linecard-CPU-FPC$FPC_No$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MEM LOAD FPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "MEM Load $tag_service",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'MEM_FPC') AND $timeFilter GROUP BY time($__interval), \"service\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MEM_FPC" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Linecard-MEM-FPC$FPC_No$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TEMPERATURE FPC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature $tag_service",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "TEMP_FPC" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Linecard-TEMP-FPC$FPC_No$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Bandwith", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Minimum Sampling Interval In \"Inbit\" series",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(mean) FROM (SELECT mean(elapsed) FROM (SELECT ELAPSED(\"value\", 1m) FROM $rp.\"Interface-check-command\" WHERE \"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No.*$/ AND \"metric\" = 'in_bits' AND $timeFilter group by service) GROUP BY service);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Maximum Sampling Interval In \"Inbit\" series",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(mean) FROM (SELECT mean(elapsed) FROM (SELECT ELAPSED(\"value\", 1m) FROM $rp.\"Interface-check-command\" WHERE \"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No.*$/ AND \"metric\" = 'in_bits' AND $timeFilter group by service) GROUP BY service);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minimum Sampling Interval In \"Outbit\" series",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(mean) FROM (SELECT mean(elapsed) FROM (SELECT ELAPSED(\"value\", 1m) FROM $rp.\"Interface-check-command\" WHERE \"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No.*$/ AND \"metric\" = 'out_bits' AND $timeFilter group by service) GROUP BY service);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Maximum Sampling Interval In \"Outbit\" series",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(mean) FROM (SELECT mean(elapsed) FROM (SELECT ELAPSED(\"value\", 1m) FROM $rp.\"Interface-check-command\" WHERE \"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No.*$/ AND \"metric\" = 'out_bits' AND $timeFilter group by service) GROUP BY service);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inbit Total- FPC $FPC_No",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "repeat": "FPC_No",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$hostname Inbit FPC$FPC_No MIC0",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM $rp.\"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No\\/0.*$/ AND \"metric\" = 'in_bits') AND $timeFilter GROUP BY time($sampling), service) GROUP BY time($sampling);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^*.(et|ge|xe)-$FPC_No\\/0.*$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" }
     ]
    },
    {
     "alias": "$hostname Inbit FPC$FPC_No MIC1",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM $rp.\"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No\\/1.*$/ AND \"metric\" = 'in_bits') AND $timeFilter GROUP BY time($sampling), service) GROUP BY time($sampling);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^*.(et|ge|xe)-$FPC_No\\/1.*$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" }
     ]
    },
    {
     "alias": "$hostname Inbit FPC$FPC_No MIC2",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM $rp.\"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No\\/2.*$/ AND \"metric\" = 'in_bits') AND $timeFilter GROUP BY time($sampling), service) GROUP BY time($sampling);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^*.(et|ge|xe)-$FPC_No\\/2.*$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" }
     ]
    },
    {
     "alias": "$hostname Inbit FPC$FPC_No MIC3",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM $rp.\"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No\\/3.*$/ AND \"metric\" = 'in_bits') AND $timeFilter GROUP BY time($sampling), service) GROUP BY time($sampling);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^*.(et|ge|xe)-$FPC_No\\/3.*$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" }
     ]
    }
   ]
  },
  {
   "title": "Outbit Total- FPC $FPC_No",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "repeat": "FPC_No",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$hostname Outbit FPC$FPC_No MIC0",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM $rp.\"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No\\/0.*$/ AND \"metric\" = 'out_bits') AND $timeFilter GROUP BY time($sampling), service) GROUP BY time($sampling);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^*.(et|ge|xe)-$FPC_No\\/0.*$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" }
     ]
    },
    {
     "alias": "$hostname Outbit FPC$FPC_No MIC1",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM $rp.\"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No\\/1.*$/ AND \"metric\" = 'out_bits') AND $timeFilter GROUP BY time($sampling), service) GROUP BY time($sampling);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^*.(et|ge|xe)-$FPC_No\\/1.*$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" }
     ]
    },
    {
     "alias": "$hostname Outbit FPC$FPC_No MIC2",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM $rp.\"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No\\/2.*$/ AND \"metric\" = 'out_bits') AND $timeFilter GROUP BY time($sampling), service) GROUP BY time($sampling);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^*.(et|ge|xe)-$FPC_No\\/2.*$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" }
     ]
    },
    {
     "alias": "$hostname Outbit FPC$FPC_No MIC3",
     "groupBy": [
      { "params": [ "$sampling" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM $rp.\"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" =~ /^*.(et|ge|xe)-$FPC_No\\/3.*$/ AND \"metric\" = 'out_bits') AND $timeFilter GROUP BY time($sampling), service) GROUP BY time($sampling);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^*.(et|ge|xe)-$FPC_No\\/3.*$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" }
     ]
    }
   ]
  }
 ]
}