{
 "title": "Bandwidth-Report-Detail",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "SHOW datasources;" },
   {
    "name": "hostgroup",
    "label": "Hostgroup",
    "query": "SELECT hostgroups.name FROM ${datasource:csv};"
   },
   {
    "name": "device_type",
    "label": "Device Type",
    "query": "SELECT hosts.vars.device_type FROM $datasource;"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SELECT hosts.display_name FROM $datasource WHERE vars.device_type = $device_type AND groups ~ (${hostgroup:pipe})"
   },
   {
    "name": "service",
    "label": "Interface",
    "query": "SELECT services.display_name FROM $datasource WHERE host_name ~ (${hostname:pipe});"
   },
   { "name": "downsampling", "label": "Downsampling Period", "query": "1d, 3d, 1w, 2w, 4w, 8w" },
   {
    "name": "rp",
    "query": "select rp from forever.rp_config where  ($__to - $__from > \"start\") and ($__to - $__from <= \"end\")"
   }
  ]
 },
 "panels": [
  {
   "title": "GraphQL MAX Bandwidth Report ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "port",
     "endTimePath": "endTime",
     "queryText": "query {\r\n        port(livestatusds: \"LiveStatus\", influxds: \"InfluxdbDatasource\", \r\n          \t\tmeasurement: \"Interface-check-command\", \r\n          \t\tfilter: \"host_name ~ (${hostname:pipe}) and display_name ~ IfCheck-$service\", \r\n              start: $__from, stop: $__to, timezone: \"Asia/Bangkok\") {\r\n\r\n              host_name\r\n              bandwidth {   display_name\r\n                \t\t\t\t\t\tmax_inbits_value {\r\n                                                time\r\n                                                value\r\n                                             }\r\n                \t\t\t\t\t\tmax_outbits_value{\r\n                              \t\t\t\t\t\t\t\t\ttime\r\n                              \t\t\t\t\t\t\t\t\tvalue\r\n                            \t\t\t\t\t\t\t\t }\r\n                    \t\t}\r\n              }\r\n    \t}\r\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "GraphQL MEAN Bandwidth Report ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "port",
     "endTimePath": "endTime",
     "queryText": "query {\r\n        port(livestatusds: \"LiveStatus\", influxds: \"InfluxdbDatasource\", \r\n          \t\tmeasurement: \"Interface-check-command\", \r\n          \t\tfilter: \"host_name ~ (${hostname:pipe}) and display_name ~ IfCheck-$service\", \r\n              start: $__from, stop: $__to, timezone: \"Asia/Bangkok\") {\r\n\r\n              host_name\r\n              bandwidth {   display_name\r\n                \t\t\t\t\t\tmean_inbits_value {\r\n                                                time\r\n                                                value\r\n                                             }\r\n                \t\t\t\t\t\tmean_outbits_value{\r\n                              \t\t\t\t\t\t\t\t\ttime\r\n                              \t\t\t\t\t\t\t\t\tvalue\r\n                            \t\t\t\t\t\t\t\t }\r\n                    \t\t}\r\n              }\r\n    \t}\r\n",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "MAX Bandwidth Report ",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT max(\"value\") AS \"Max_Bandwidth\" FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^IfCheck-[[service]]$/ AND \"state\" = 'OK') AND $timeFilter GROUP BY \"hostname\", \"metric\", \"service\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max_Bandwidth" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^inbits|^out_bits/" }
     ]
    }
   ]
  },
  {
   "title": "AVERGAE Bandwidth Report ",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT max(\"value\") AS \"Max_Bandwidth\" FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^IfCheck-[[service]]$/ AND \"state\" = 'OK') AND $timeFilter GROUP BY \"hostname\", \"metric\", \"service\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Max_Bandwidth" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^inbits|^out_bits/" }
     ]
    }
   ]
  },
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "hostname" },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "repeat": "service",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$service (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "$service (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    }
   ]
  },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$service (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "$service (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    }
   ]
  },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$service (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "$service (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    }
   ]
  },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$service (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "$service (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    }
   ]
  },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$service (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "$service (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    }
   ]
  },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$service (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "$service (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (IN)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    },
    {
     "alias": "MAX POINT (OUT)",
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[service]]$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "44023414784" }
     ]
    }
   ]
  }
 ]
}