{
 "title": "Device Dashboard Overview",
 "tags": [ "host_info" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "SHOW datasources;" },
   {
    "name": "hostgroup",
    "label": "Hostgroup",
    "query": "SELECT hostgroups.name FROM ${datasource:csv};"
   },
   { "name": "hoststate", "label": "Hoststate", "query": "show hoststate;" },
   {
    "name": "device_type",
    "label": "Device Type",
    "query": "SELECT hosts.vars.device_type FROM ${datasource:csv};"
   },
   {
    "name": "hostname",
    "label": "Device name",
    "query": "SELECT hosts.display_name FROM ${datasource:csv} WHERE state ~ (${hoststate:pipe}) AND groups ~ (${hostgroup:pipe}) AND vars.device_type = ${device_type:pipe};"
   },
   {
    "name": "address",
    "label": "IP address",
    "query": "SHOW TAG VALUES from hostalive  WITH KEY = \"address\" where device_type =~ /$device_type/  and hostname =~ /$hostname/ "
   },
   {
    "name": "interface",
    "label": "Interface-check",
    "query": "SHOW TAG VALUES from /Interface-check-command/ WITH KEY = \"service\" where hostname =~ /$hostname/ "
   },
   {
    "name": "FPC",
    "label": "FPC",
    "query": "show tag values with key = \"service\";"
   },
   {
    "name": "rp",
    "query": "select rp from forever.rp_config where  ($__to - $__from > \"start\") and ($__to - $__from <= \"end\")"
   }
  ]
 },
 "panels": [
  { "title": "$hostname - $address", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "STATUS",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hostalive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
     ]
    }
   ]
  },
  {
   "title": "Ping4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "RTA" }
   ],
   "targets": [
    {
     "alias": "RTA",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"value\") FROM \"$rp\".\"ping4\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'rta') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Load $tag_metric",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"value\") FROM \"$rp\".\"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^*.CPU.*/ AND \"metric\" =~ /^.*RE.*$/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^*.CPU.*/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^.*RE.*$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory $tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT max(\"value\") FROM \"$rp\".\"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^Juniper.*.Memory.*/ AND \"metric\" =~ /^.*RE.*$/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Memory.*/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^.*RE.*$/" }
     ],
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "TEMPERATURE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature $tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Temperature.*/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/.*RE.*/" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "Temperature $tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Temperature.*/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/.*Chassis.*/" }
     ],
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU LOAD FPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Load $tag_service",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CPU_FPC" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MEM LOAD FPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "MEM Load $tag_service",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MEM_FPC" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TEMPERATURE FPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature $tag_service",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "TEMP_FPC" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Bandwith", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "BandwidthTotal",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$hostname-total-InBit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "service", "operator": "!~", "value": "/.*.ae.*./" }
     ]
    },
    {
     "alias": "$hostname-total-OutBit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "service", "operator": "!~", "value": "/.*.ae.*./" }
     ]
    }
   ]
  },
  {
   "title": "BandwidthSpecific-$interface",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "repeat": "interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$hostname-$interface-InBit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"Interface-check-command\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'in_bits' AND \"service\" =~ /^IfCheck-[[interface]]$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[interface]]$/" }
     ]
    },
    {
     "alias": "$hostname-$interface-OutBit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[interface]]$/" }
     ]
    }
   ]
  }
 ]
}