{
 "title": "Device Dashboard Detail",
 "tags": [ "host_info" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "SHOW datasources;" },
   {
    "name": "hostgroup",
    "label": "Hostgroup",
    "query": "SELECT hostgroups.name FROM ${datasource:csv};"
   },
   { "name": "hoststate", "label": "Hoststate", "query": "show hoststate;" },
   {
    "name": "device_type",
    "label": "Device Type",
    "query": "SELECT hosts.vars.device_type FROM ${datasource:csv};"
   },
   {
    "name": "hostname",
    "label": "Device name",
    "query": "SELECT hosts.display_name FROM ${datasource:csv} WHERE state ~ (${hoststate:pipe}) AND groups ~ (${hostgroup:pipe}) AND vars.device_type = ${device_type:pipe};"
   },
   {
    "name": "address",
    "label": "IP address",
    "query": "SHOW TAG VALUES from hostalive  WITH KEY = \"address\" where device_type =~ /$device_type/  and hostname =~ /$hostname/ "
   },
   {
    "name": "interface",
    "label": "Interface-check",
    "query": "SHOW TAG VALUES from /Interface-check-command/ WITH KEY = \"service\" where hostname =~ /$hostname/ "
   },
   {
    "name": "FPC",
    "label": "FPC",
    "query": "show tag values with key = \"service\";"
   },
   {
    "name": "rp",
    "query": "select rp from forever.rp_config where  ($__to - $__from > \"start\") and ($__to - $__from <= \"end\")"
   }
  ]
 },
 "panels": [
  { "title": "Overview information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SERVICE OK",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "query": {
      "datasource": [
       "services",
       "COUNT",
       "FROM",
       "${datasource:csv}"
      ],
      "hostFilter": [],
      "serviceFilter": []
     },
     "segments": [
      "COUNT",
      "FROM",
      "${datasource:csv}",
      "WHERE",
      "host_name",
      "=",
      "$hostname",
      "AND",
      "state",
      "=",
      "0",
      "*"
     ],
     "target": "services",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SERVICE WARNING",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "query": {
      "datasource": [
       "services",
       "COUNT",
       "FROM",
       "${datasource:csv}"
      ],
      "hostFilter": [],
      "serviceFilter": []
     },
     "segments": [
      "COUNT",
      "FROM",
      "${datasource:csv}",
      "WHERE",
      "host_name",
      "=",
      "$hostname",
      "AND",
      "state",
      "=",
      "1",
      "*"
     ],
     "target": "services",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SERVICE CRITICAL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "query": {
      "datasource": [
       "services",
       "COUNT",
       "FROM",
       "${datasource:csv}"
      ],
      "hostFilter": [],
      "serviceFilter": []
     },
     "segments": [
      "COUNT",
      "FROM",
      "${datasource:csv}",
      "WHERE",
      "host_name",
      "=",
      "$hostname",
      "AND",
      "state",
      "=",
      "2",
      "*"
     ],
     "target": "services",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SERVICE UNKNOWN",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "query": {
      "datasource": [
       "services",
       "COUNT",
       "FROM",
       "${datasource:csv}"
      ],
      "hostFilter": [],
      "serviceFilter": []
     },
     "segments": [
      "COUNT",
      "FROM",
      "${datasource:csv}",
      "WHERE",
      "host_name",
      "=",
      "$hostname",
      "AND",
      "state",
      "=",
      "3",
      "*",
      "*",
      "*"
     ],
     "target": "services",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Host Detail Information",
   "type": "icinga2-report-panel-transposed",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "query": {
      "datasource": [
       "hosts",
       "SELECT",
       "action_url_expanded",
       "display_name",
       "address",
       "check_command_expanded",
       "state",
       "state_type",
       "notifications_enabled",
       "plugin_output",
       "last_check",
       "last_state_change",
       "perf_data",
       "process_performance_data",
       "check_type",
       "last_hard_state",
       "last_hard_state_change",
       "last_notification",
       "current_notification_number",
       "next_check",
       "has_been_checked",
       "check_period",
       "check_interval",
       "retry_interval",
       "execution_time",
       "total_services",
       "num_services_hard_ok",
       "num_services_hard_warn",
       "num_services_hard_crit",
       "num_services_hard_unknown",
       "groups",
       "FROM",
       "$datasource",
       "*"
      ],
      "hostFilter": [],
      "serviceFilter": []
     },
     "segments": [
      "SELECT",
      "action_url_expanded",
      "display_name",
      "address",
      "check_command_expanded",
      "state",
      "state_type",
      "notifications_enabled",
      "plugin_output",
      "last_check",
      "last_state_change",
      "perf_data",
      "process_performance_data",
      "check_type",
      "last_hard_state",
      "last_hard_state_change",
      "last_notification",
      "current_notification_number",
      "next_check",
      "has_been_checked",
      "check_period",
      "check_interval",
      "retry_interval",
      "execution_time",
      "total_services",
      "num_services_hard_ok",
      "num_services_hard_warn",
      "num_services_hard_crit",
      "num_services_hard_unknown",
      "groups",
      "FROM",
      "$datasource",
      "WHERE",
      "display_name",
      "=",
      " $hostname",
      "*"
     ],
     "target": "hosts",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ACTIONS",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 3 },
   "content": "<div align=\"center\">\n<button onClick=\"send_command('SCHEDULE_FORCED_HOST_CHECK', host, livestatus_name)\" style=\"color: black\">Force Check</button>\n<button onClick=\"send_command('ENABLE_HOST_NOTIFICATIONS', host, livestatus_name)\" style=\"color: black\">Enable Notification</button>\n<button onClick=\"send_command('DISABLE_HOST_NOTIFICATIONS', host, livestatus_name)\" style=\"color: black\">Disable Notification</button>\n<script type=\"text/javascript\">\n  var host = '$hostname';\n  var datasource = '$grafana_ds';\n  var livestatus_name = '$datasource';\n  var service ='ping4';\nfunction getURL() {\n    source_url = window.location;\n}\ngetURL();\nfunction send_command(type, host, livestatus_name) {\n  //Get the url datasource in grafana - Start\n  var r = confirm(\"Do you want to send the '\" + type + \"' command to livestatus ?\");\n  if (r == true) {\n    var req = new XMLHttpRequest();\n    req.open(\"GET\", \"/grafana/api/datasources/name/\" + datasource, false);\n    req.send(null);\n    console.log(req.status);\n    if (req.status == \"200\") {\n      var obj = JSON.parse(req.responseText);\n      var url = \"\";\n      url = source_url.protocol + \"//\" + source_url.host + \"/grafana/send_request/api/v1/\" + obj.name + \"/command?type=\" + encodeURIComponent(type) + \"&host=\" + encodeURIComponent(host) + \"&service=\" + encodeURIComponent(service) + \"&livename=\" + encodeURIComponent(livestatus_name);\n      console.log(url);\n      req.open(\"GET\", url, true);\n      req.addEventListener('load', function(){\n        console.log(req.status);\n        console.log(req.responseText);\n        setTimeout(continueExecution, 1000);\n      });\n      req.send(null);\n    }\n    else {\n      console.log(\"Error\");\n    }\n  }\n}\nfunction continueExecution() {\n  history.go(0);\n}\n</script>"
  },
  {
   "title": "Services Informations",
   "type": "table-old",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": {
      "datasource": [
       "services",
       "SELECT",
       "display_name",
       "host_name",
       "state",
       "state_type",
       "last_check",
       "plugin_output",
       "action_url_expanded",
       "FROM",
       "${datasource:csv}"
      ],
      "hostFilter": [],
      "serviceFilter": []
     },
     "segments": [
      "SELECT",
      "display_name",
      "host_name",
      "state",
      "last_check",
      "plugin_output",
      "FROM",
      "LiveStatus",
      "WHERE",
      "host_name",
      "=",
      "$hostname",
      "*",
      "*",
      "*",
      "*"
     ],
     "target": "services",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "$hostname - $address",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "hostname",
   "collapsed": true,
   "panels": [
    {
     "title": "STATUS",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "hostalive",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
       ]
      }
     ]
    },
    {
     "title": "Ping4",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 28 },
     "yaxes": [
      { "format": "s", "label": "RTA" }
     ],
     "targets": [
      {
       "alias": "RTA",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "ping4",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT mean(\"value\") FROM \"ping4\" WHERE (\"metric\" = 'pl' AND \"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" }
       ],
       "timeField": "@timestamp"
      },
      {
       "alias": "PL",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "ping4",
       "query": "SELECT mean(\"value\") FROM \"ping4\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'pl') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
       ]
      }
     ]
    },
    {
     "title": "CPU LOAD RE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_service",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^CPU.*.RE.*/" },
        { "condition": "AND", "key": "metric", "operator": "!~", "value": "/^CPU.*.RE\\d_mem\\d.*/" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "MEMORY RE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_service",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /Juniper Memory~/ AND \"metric\" = 'MEM_RE0') AND $timeFilter GROUP BY time($__interval) fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^MEM.*.RE.*/" },
        { "condition": "AND", "key": "metric", "operator": "!~", "value": "/^MEM.*.RE\\d_mem\\d.*/" }
       ],
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "TEMPERATURE RE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "$tag_service",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=~", "value": "/TEMP.*.RE.*/" },
        { "condition": "AND", "key": "metric", "operator": "!~", "value": "/^TEMP.*.RE\\d_mem\\d.*/" }
       ],
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU LOAD FPC",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPU Load $tag_service",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "CPU_FPC" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "MEM LOAD FPC",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "MEM Load $tag_service",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT last(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'MEM_FPC') AND $timeFilter GROUP BY time($__interval), \"service\" fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "MEM_FPC" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "TEMPERATURE FPC",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "Temperature $tag_service",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "TEMP_FPC" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "PEM Output Power",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "alias": "$tag_metric",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "check_netconf_tableview",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "service", "operator": "=", "value": "NETCONF-POWER" },
        { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^.*Power.*$/" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Bandwith", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "BandwidthTotal",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$hostname-total-InBit",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "service", "operator": "!~", "value": "/.*.ae.*./" }
     ]
    },
    {
     "alias": "$hostname-total-OutBit",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "service", "operator": "!~", "value": "/.*.ae.*./" }
     ]
    }
   ]
  },
  {
   "title": "BandwidthSpecific-$interface",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "repeat": "interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$hostname-$interface-InBit",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[interface]]$/" }
     ]
    },
    {
     "alias": "$hostname-$interface-OutBit",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[interface]]$/" }
     ]
    }
   ]
  }
 ]
}