{
 "title": "Host Groups Overview",
 "tags": [ "host_info" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "SHOW datasources;" },
   {
    "name": "hostgroup",
    "label": "Hostgroup",
    "query": "SELECT hostgroups.name FROM ${datasource:csv};"
   },
   { "name": "hoststate", "label": "Host State", "query": "show hoststate;" },
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT hosts.display_name FROM ${datasource:csv} WHERE state ~ (${hoststate:pipe}) AND groups ~ (${hostgroup:pipe});"
   },
   { "name": "servicestate", "label": "Service State", "query": "show servicestate;" }
  ]
 },
 "panels": [
  {
   "title": "Hostgroup Summary Per Item",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": {
      "datasource": [
       "hostgroups",
       "SELECT",
       "name",
       "num_hosts_up",
       "num_hosts_down",
       "num_hosts_unreach",
       "num_hosts",
       "num_services_ok",
       "num_services_warn",
       "num_services_crit",
       "num_services_unknown",
       "num_services",
       "FROM",
       "${datasource:csv}"
      ],
      "hostFilter": [],
      "serviceFilter": []
     },
     "segments": [
      "SELECT",
      "name",
      "num_hosts_up",
      "num_hosts_down",
      "num_hosts_unreach",
      "num_hosts",
      "num_services_ok",
      "num_services_warn",
      "num_services_crit",
      "num_services_unknown",
      "num_services",
      "FROM",
      "${datasource:csv}",
      "WHERE",
      "name",
      "~",
      "(${hostgroup:pipe})",
      "*"
     ],
     "target": "hostgroups",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Host Status Details For All Host Groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": {
      "datasource": [
       "hosts",
       "SELECT",
       "action_url_expanded",
       "display_name",
       "state",
       "last_check",
       "plugin_output",
       "FROM",
       "${datasource:csv}"
      ],
      "hostFilter": [],
      "serviceFilter": []
     },
     "segments": [
      "SELECT",
      "action_url_expanded",
      "display_name",
      "state",
      "last_check",
      "plugin_output",
      "FROM",
      "${datasource:csv}",
      "WHERE",
      "display_name",
      "~",
      "(${host:pipe})",
      "AND",
      "groups",
      "~",
      "(${hostgroup:pipe})",
      "AND",
      "state",
      "~",
      "(${hoststate:pipe})",
      "*",
      "*",
      "*"
     ],
     "target": "hosts",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Services Informations For All Host Groups",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": {
      "datasource": [
       "services",
       "SELECT",
       "display_name",
       "host_name",
       "state",
       "state_type",
       "last_check",
       "plugin_output",
       "action_url_expanded",
       "FROM",
       "${datasource:csv}"
      ],
      "hostFilter": [],
      "serviceFilter": []
     },
     "segments": [
      "SELECT",
      "display_name",
      "host_name",
      "state",
      "state_type",
      "last_check",
      "plugin_output",
      "action_url_expanded",
      "FROM",
      "${datasource:csv}",
      "WHERE",
      "host_name",
      "~",
      "(${host:pipe})",
      "AND",
      "host_state",
      "~",
      "(${hoststate:pipe})",
      "AND",
      "state",
      "~",
      "(${servicestate:pipe})",
      "AND",
      "host_groups",
      "~",
      "(${hostgroup:pipe})",
      "*",
      "*"
     ],
     "target": "services",
     "type": "timeserie"
    }
   ]
  }
 ]
}