{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Hypervisor Overview Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 98%;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  position: absolute;\n  left: 50%;\n  top: 50%;\n  -ms-transform: translate(-50%, -50%);\n  transform: translate(-50%, -50%);\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: #696969;\n  color: white;\n  border:1px solid #696969;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('d/wyXTOna4z/menu?orgId=1', '_self')\"><span>&equiv; MENU</span></button>\n\n</body>\n</html>"
   }
  },
  {
   "title": "Hypervisors Overview Information",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "VM Counter (Clickable)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "target_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:vmware_total_host" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total_host" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "target_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:proxmox_total_host" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total_host" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "target_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:vmware_host_down" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "host_down" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "target_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:proxmox_host_down" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "host_down" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hypervisor Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:vmware_cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "vmware" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:proxmox_cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "pve" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hypervisor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:vmware_memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "vmware" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:proxmox_memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "pve" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Overview Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    { "title": "Host's Resource Information", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
    { "title": "Hosts state information", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 21 } },
    {
     "title": "Top hosts by cpu and memory usage (Clickable)",
     "type": "table",
     "gridPos": { "h": 14, "w": 9, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "alias": "cpu",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "prometheus_remote_write",
       "query": "SELECT 1 - mean(cpu_usage) AS mean_cpu_usage FROM \n(\nSELECT (last(\"node_cpu_seconds_total\") - first(\"node_cpu_seconds_total\")) / count(\"node_cpu_seconds_total\") / 15 AS cpu_usage\n  FROM \"prometheus_remote_write\"\n  WHERE (\"mode\" = 'idle') AND $timeFilter\n  GROUP BY \"instance\", \"cpu\"\n) GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "job:node_cpu_usage" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "memory",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "prometheus_remote_write",
       "query": "SELECT  1 - max(\"node_memory_MemAvailable_bytes\") / max(\"node_memory_MemTotal_bytes\") FROM \"prometheus_remote_write\" WHERE $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "job:node_memory_usage" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top hosts by disk usage (Clickable)",
     "type": "table",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "limit": "1",
       "measurement": "prometheus_remote_write",
       "query": "SELECT * FROM (SELECT 1 - sum(b) / sum(a) as c FROM (SELECT mean(\"node_filesystem_size_bytes\") as a, mean(\"node_filesystem_avail_bytes\") as b FROM \"prometheus_remote_write\" WHERE $timeFilter GROUP BY \"instance\", \"mountpoint\") GROUP BY \"instance\") WHERE c > 0.5",
       "select": [
        [
         { "params": [ "job:node_disk_usage" ], "type": "field" }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "limit": "1",
       "measurement": "prometheus_remote_write",
       "select": [
        [
         { "params": [ "node_filesystem_size_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total hosts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "prometheus_remote_write",
       "query": "SELECT count(c) FROM (SELECT last(\"up\") as c FROM \"prometheus_remote_write\" WHERE \"job\" = 'node_exporter' AND $timeFilter GROUP BY \"instance\" LIMIT 1)",
       "select": [
        [
         { "params": [ "job:node_total_hosts" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Host down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "prometheus_remote_write",
       "query": "SELECT \"up\" FROM \"prometheus_remote_write\" WHERE (\"up\" = 0) AND $timeFilter GROUP BY \"instance\" LIMIT 1",
       "select": [
        [
         { "params": [ "job:node_host_down" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "List of host down",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "prometheus_remote_write",
       "query": "SELECT last(\"up\") FROM \"prometheus_remote_write\" WHERE (\"job\" = 'node_exporter' AND \"up\" = 0) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "up" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "job", "operator": "=", "value": "node_exporter" }
       ]
      }
     ]
    }
   ]
  }
 ]
}