{
 "title": "Node Information",
 "tags": [ "node_overview" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", instance=~\"$node\"}, nodename)"
    }
   },
   { "name": "warning", "label": "Warning Threshold", "query": "70" },
   {
    "name": "address",
    "label": "IP Address",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", instance=~\"$node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "type": "aidanmountford-html-panel", "format": "short" },
  { "type": "aidanmountford-html-panel", "gridPos": { "h": 3, "w": 6, "x": 17, "y": 0 }, "format": "short" },
  {
   "title": "Overview Infomation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OS Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "domainname" ], "type": "tag" },
      { "params": [ "machine" ], "type": "tag" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "sysname" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "node_uname_info" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage > $warning%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(100 - (avg(irate(node_cpu_seconds_total{job=~\"$job\", instance=~\"$node\",mode=\"idle\"}[5m])) by (instance)* 100)  > $warning)"
    }
   ]
  },
  {
   "title": "CPU IOWait > $warning%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((avg(irate(node_cpu_seconds_total{job=~\"$job\", instance=~\"$node\",mode=\"iowait\"}[5m])) by (instance)* 100)  > $warning)"
    }
   ]
  },
  {
   "title": "Used RAM > $warning%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((1 - (node_memory_MemAvailable_bytes{instance=~\"$node\", job=~\"$job\"} / (node_memory_MemTotal_bytes{instance=~\"$node\", job=~\"$job\"})))* 100 > $warning)"
    }
   ]
  },
  {
   "title": "Used Disk > $warning%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(100 - ((node_filesystem_avail_bytes{instance=~\"$node\", job=~\"$job\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\", job=~\"$job\"}) > $warning)"
    }
   ]
  },
  {
   "title": "Detail information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\", instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Node name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\",instance=~\"$node\"}",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\", job=~\"$job\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$node\", job=~\"$job\"} / node_memory_SwapTotal_bytes{instance=~\"$node\", job=~\"$job\"})) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\", job=~\"$job\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\",mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "IOWait"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", job=~\"$job\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\", job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\" ,job=~\"$job\"}-0"
    },
    {
     "expr": "(node_filesystem_avail_bytes{instance=~\"$node\" ,job=~\"$job\"})-0"
    },
    {
     "expr": "(1-(node_filesystem_avail_bytes{instance=~\"$node\" ,job=~\"$job\"} / node_filesystem_size_bytes{instance=~\"$node\" ,job=~\"$job\"}))-0"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\"}[$__range])) by (mode) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Interface receive traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance =~ \"$node\",device=~'ens.*|eno.*|eth.*|enp.*'}[$__range])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IO (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$node\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"$node\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}