# Module: system
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.10/metricbeat-module-system.html

- module: system
  period: 30s
  metricsets:
    - cpu
    - load
    - memory
    - network
    #- entropy
    #- core
    - diskio
    #- socket
    #- service
    #- users

- module: system
  period: 1m
  metricsets:
    - process
    - process_summary
    - socket_summary
    - filesystem
    - fsstat
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime

#- module: system
#  period: 5m
#  metricsets:
#    - raid
#  raid.mount_point: '/'
