{
 "title": "HOME",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": "{\"find\": \"terms\", \"field\": \"fields.group\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  { "title": "System Overview Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 98%;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  position: absolute;\n  left: 50%;\n  top: 50%;\n  -ms-transform: translate(-50%, -50%);\n  transform: translate(-50%, -50%);\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: #696969;\n  color: white;\n  border:1px solid #696969;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/grafana/d/menu/menu?orgId=1', '_blank')\"><span>&equiv; MENU</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 98%;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  position: absolute;\n  left: 50%;\n  top: 50%;\n  -ms-transform: translate(-50%, -50%);\n  transform: translate(-50%, -50%);\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: #696969;\n  color: white;\n  border:1px solid #696969;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/kibana/app/management/insightsAndAlerting/triggersActions/alerts', '_blank')\"><span>&#9888; Alerts and Actions</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hosts' Resource Informations",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "options": { "content": " " },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hosts State Informations",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 5 },
   "options": { "content": " " },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Hosts by CPU and Memory Usage (Clickable)",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 13, "w": 10, "x": 6, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:586",
       "field": "host.name",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "system.cpu.total.norm.pct",
       "id": "1",
       "settings": {},
       "type": "max"
      },
      {
       "field": "system.memory.actual.used.pct",
       "id": "3",
       "settings": {},
       "type": "max"
      },
      { "field": "system.load.5", "id": "4", "type": "max" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts by Partition Usage > 40% (Clickable)",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.filesystem.mount_point",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "host.name",
       "id": "5",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "system.filesystem.used.pct", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Host",
   "type": "stat",
   "description": "Number of Total Hosts",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3102",
       "field": "host.name",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3118",
       "field": "host.name",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hosts DOWN",
   "type": "stat",
   "description": "Number of Host Down",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3292",
       "fake": true,
       "field": "host.name",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "host.name", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "List of Hosts DOWN (Clickable)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3292",
       "fake": true,
       "field": "host.name",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:428",
       "field": "host.name",
       "id": "1",
       "meta": {},
       "settings": {
        "precision_threshold": null
       },
       "type": "cardinality"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Number Of Services UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.full",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "url.full", "id": "1", "type": "cardinality" }
     ],
     "query": "summary.up: \"1\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number Of Services DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.full",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "url.full", "id": "1", "type": "cardinality" }
     ],
     "query": "summary.up: \"0\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alert Logs",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 19 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Detail Of Services States",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.domain",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "summary.up: \"0\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "AAA Overview Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Authentication Accept (last 5m)",
   "type": "stat",
   "description": "Sum Of Current Accept Transaction",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.authentication.data.authentication.accept_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.authentication\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Authentication Reject (last 5m)",
   "type": "stat",
   "description": "Sum Of Current Reject Transaction",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.authentication.data.authentication.reject_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.authentication\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AAA MySQL / MariaDB Table Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "6", "type": "logs" }
     ],
     "query": "event.dataset:mysql.galera_status AND fields.group: [[group]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accouting Starts (last 5m)",
   "type": "stat",
   "description": "Sum Of Current Starts Transaction",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_start_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accouting Stops (last 5m)",
   "type": "stat",
   "description": "Sum Of Current Stops Transaction [[hostname]]",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_stop_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accouting Interim (last 5m)",
   "type": "stat",
   "description": "Sum Of Current Interim",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_interim_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MariaDB-Number of Slow Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "mysql.slowlog.query",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Authentication Accept Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.authentication.data.authentication.accept_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.authentication\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accounting Starts Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_start_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Authentication Reject Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.authentication.data.authentication.reject_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.authentication\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accounting Stop Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_stop_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accounting Interim Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "http.accounting.data.accounting.acct_interim_current_rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "metricset.name: json AND event.dataset: \"http.accounting\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "History of Top Hosts by Resource Usage ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 }
  },
  {
   "title": "Top Hosts by CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.total.norm.pct",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts by Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.pct",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Host by Disk IO - READ (Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "host.name", "id": "7", "settings": { "order": "desc", "orderBy": "1", "size": "5" }, "type": "terms" },
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.diskio.read.bytes",
       "hide": true,
       "id": "1",
       "settings": { "script": "_value / 10" },
       "type": "max"
      },
      {
       "field": "1",
       "id": "6",
       "pipelineAgg": "1",
       "settings": { "unit": "10s" },
       "type": "derivative"
      }
     ],
     "query": "-system.network.name:l*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Host by Disk IO - WRITE (Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.diskio.write.bytes",
       "hide": true,
       "id": "1",
       "settings": { "script": "_value / 10" },
       "type": "max"
      },
      {
       "field": "1",
       "id": "6",
       "pipelineAgg": "1",
       "settings": { "unit": "30s" },
       "type": "derivative"
      }
     ],
     "query": "-system.network.name:l*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}