---
# Wrote by Hoang Anh Tu
  - name: GRAFANA - INSTALLATION [STEP 01] - Install Grafana
    yum:
#      name: "{{ item.package }}"
#      state: latest
#    with_items: "{{ grafana_yum }}"
      name: https://dl.grafana.com/oss/release/grafana-7.0.3-1.x86_64.rpm
      state: present

  - name: GRAFANA - CONFIGURATION [Step 02] - Configure Grafana MariaDB
    replace:
      dest: /etc/grafana/grafana.ini
      regexp: "{{ item.old }}"
      replace: "{{ item.new }}"
      backup: yes
    with_items:
#      - { old: ";root_url = http://localhost:3000", new: 'root_url = %(protocol)s://%(domain)s/grafana/'}
      - { old: ";root_url = .*", new: 'root_url = %(protocol)s://%(domain)s/grafana/'}
      - { old: ";type = sqlite3", new: 'type = mysql'}
      - { old: ";host = 127.0.0.1:3306", new: 'host = 127.0.0.1:3306'}
      - { old: ";name = grafana", new: 'name = {{ grafana_database }}'}
      - { old: ";user = root", new: 'user = {{ grafana_database_user }}'}
      - { old: ";password =", new: 'password = {{ grafana_database_password }}'}
      - { old: ";admin_user = admin", new: 'admin_user = {{ grafana_admin_user }}'}
      - { old: ";admin_password = admin", new: 'admin_password = {{ grafana_admin_password }}'}
      - { old: ";header_name = X-WEBAUTH-USER", new: 'header_name = X-WEBAUTH-USER'}
      - { old: ";header_property = username", new: 'header_property = username'}
      - { old: ";allow_embedding = false", new: 'allow_embedding = true' }
      - { old: ";disable_sanitize_html = false", new: 'disable_sanitize_html = true' }

#  - name: GRAFANA - CONFIGURATION [STEP 03] - Enable Apache auth for Grafana
#    lineinfile:
#      dest: /etc/grafana/grafana.ini
#      insertafter: "[auth.proxy"
#      line: 'enabled = true'
#      state: present

  - name: GRAFANA - CONFIGURATION [STEP 04] - Enable anonymouse access
    lineinfile:
      dest: /etc/grafana/grafana.ini
      insertafter: '# enable anonymous access'
      line: 'enabled = true'
      state: present

  - name: GRAFANA - CONFIGURATION [STEP 05] - Starting Grafana Service
    service:
      name: grafana-server
      state: started
      enabled: yes
    failed_when: false

  - name: GRAFANA - CONFIGURATION [STEP 06] - Copy default organization into server in MariaDB database
    template:
      src: "{{ role_path }}/templates/mariadb_change_default_org.j2"
      dest: "/tmp/change_default_org.sql"

  - name: GRAFANA - CONFIGURATION [STEP 07] - Change default organization in MariaDB database
    mysql_db:
      name: "{{ grafana_database }}"
      login_user: root
      login_password: "{{ mariadb_root_password }}"
      login_host: 127.0.0.1
      state: import
      target: /tmp/change_default_org.sql

  - name: GRAFANA - CONFIGURATION [STEP 08] - Configure organization for anonymouse access
    lineinfile:
      dest: /etc/grafana/grafana.ini
      insertafter: '# specify organization name that should be used for unauthenticated users'
      line: 'org_name = {{ organization }}'
      state: present

  - name: GRAFANA - CONFIGURATION [STEP 09] - Configure role for anonymouse access
    lineinfile:
      dest: /etc/grafana/grafana.ini
      insertafter: '# specify role for unauthenticated users'
      line: 'org_role = Viewer'
      state: present
    notify:
      - Restart grafana

  # - name: GRAFANA - CONFIGURATION [STEP 10] - Copy Grafana Plugin Panel
  #   copy:
  #     src: "{{ item }}"
  #     dest: /var/lib/grafana/plugins
  #     owner: root
  #     group: root
  #     mode: 0775
  #   with_items:
  #     - "{{ role_path }}/files/icinga2_report/icinga2-report-datasource"
  #     - "{{ role_path }}/files/icinga2_report/icinga2-report-panel"
  #     - "{{ role_path }}/files/icinga2_report/icinga2_report_panel_transposed"

  # - name: GRAFANA - CONFIGURATION [STEP 11] - Copy Grafana scripted_dashboard
  #   copy:
  #     src: "{{ item }}"
  #     dest: /usr/share/grafana/public/dashboards/
  #     owner: root
  #     group: root
  #     mode: 0775
  #   with_fileglob:
  #     - "{{ role_path }}/files/grafana-entities/scripted_dashboard/*.js"

  - name: GRAFANA - CONFIGURATION [STEP 12] - Install Other Grafana Plugin Panel
    command: grafana-cli plugins install {{ item }}
    with_items:
       - briangann-datatable-panel
       - farski-blendstat-panel
       - grafana-piechart-panel
      # - michaeldmoore-multistat-panel
      # - natel-discrete-panel
      # - sni-thruk-datasource
      # - yesoreyeram-boomtable-panel
    args:
      warn: false
    notify:
      - Restart grafana

  - name: GRAFANA - CONFIGURATION [STEP 13] - Allow Grafana script tags in text panels
    lineinfile:
      path: /etc/grafana/grafana.ini
      regexp: '^;disable_sanitize_html'
      line: disable_sanitize_html = true
    notify:
      - Restart grafana
