---
# Wrote by Hoang Anh Tu
  - name: INFLUXDB - INSTALLATION [STEP 01] - Install InfluxDB
    yum:
      name: "{{ item.package }}"
      state: latest
    with_items: "{{ influxdb_yum }}"

  - name: INFLUXDB - INSTALLATION [STEP 02] - Start InfluxDB
    service:
      name: influxdb
      state: started
      enabled: yes

  - name: INFLUXDB - CONFIGURATION [Step 03] - Configure InfluxDB
    replace:
      dest: /etc/influxdb/influxdb.conf
      regexp: "{{ item.old }}"
      replace: "{{ item.new }}"
      backup: yes
    with_items:
      - { old: '# access-log-path = ""', new: 'access-log-path = "/var/log/influxdb/http_logging"'}
      - { old: '# write-tracing = false', new: 'write-tracing = true' }
      - { old: '# level = "info"', new: 'level = "warn"' }
      - { old: '# bind-address = "127.0.0.1:8088"', new: ' bind-address = "0.0.0.0:8088"' }
    notify:
      - Restart influxdb

  - meta: flush_handlers

  - name: INFLUXDB - CONFIGURATION [Step 04] - Create influxDB database and user
    command: "{{ item }}"
    with_items:
      - "influx -execute 'create database {{ influxdb_database }};'"
      - influx -execute "create user {{ influxdb_user }} with password '{{ influxdb_password }}';"
      - "influx -execute 'grant all on {{ influxdb_database }} to {{ influxdb_user }};'"
  - name: INFLUXDB - CONFIGURATION [Step 05] - Create influxDB retentions
    command: "{{ item }}"
    with_items:
      - influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'USE {{ influxdb_database }};'
      - influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'CREATE RETENTION POLICY six_months ON {{ influxdb_database }} DURATION 26w REPLICATION 1 DEFAULT;'
      - influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'CREATE RETENTION POLICY one_year ON {{ influxdb_database }} DURATION 52w REPLICATION 1;'
      - influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'CREATE RETENTION POLICY infinite_time ON {{ influxdb_database }} DURATION inf REPLICATION 1;'
      - influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'CREATE RETENTION POLICY forever ON {{ influxdb_database }} DURATION inf REPLICATION 1;'
      - influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'INSERT INTO {{ influxdb_database }}.forever rp_config,idx=1 rp="six_months",start=0i,end=15724800000i -9223372036854775806'
      - influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'INSERT INTO {{ influxdb_database }}.forever rp_config,idx=2 rp="one_year",start=15724800000i,end=31449600000i -9223372036854775806'
      - influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'INSERT INTO {{ influxdb_database }}.forever rp_config,idx=3 rp="inf_time",start=31449600000i,end=9223372036854775806i'
  - name: INFLUXDB - CONFIGURATION [Step 05] - Create influxDB continuous queries
    command: |
      influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'USE {{ influxdb_database }};'
      influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_{{ item }}" ON {{ influxdb_database }} BEGIN SELECT max(value) AS value, min(value), mean(value) INTO {{ influxdb_database }}.one_year."{{ item }}" FROM {{ influxdb_database }}.six_months."{{ item }}" GROUP BY time(30m), * END;'
      influx -username {{ influxdb_user }} -password {{ influxdb_password }} -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_{{ item }}" ON {{ influxdb_database }} BEGIN SELECT max(value) AS value, min(value), mean(value) INTO {{ influxdb_database }}.infinite_time."{{ item }}" FROM {{ influxdb_database }}.six_months."{{ item }}" GROUP BY time(1h), * END;'
    with_items:
      - "{{ common_measurements }}"
