{
 "title": "Session Information From Juniper Session DB",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "select Sbr_UserName from Sbr_CurrentSessions;"
   },
   {
    "name": "bras",
    "label": "BRAS",
    "query": "select Sbr_NasName from Sbr_CurrentSessions"
   },
   {
    "name": "field",
    "label": "Display Field",
    "query": "SELECT `COLUMN_NAME` \nFROM `INFORMATION_SCHEMA`.`COLUMNS` \nWHERE `TABLE_SCHEMA`='SteelBeltedRadius' \n    AND `TABLE_NAME`='Sbr_CurrentSessions';"
   },
   { "name": "limit", "label": "Limit Query", "query": "10,100,1000,10000" },
   { "name": "client_port", "label": "Client Port" }
  ]
 },
 "panels": [
  { "title": "Concurrent Sesion on BRAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$bras",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "bras",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "select count(Sbr_UserName) from Sbr_CurrentSessions where Sbr_NasName in ($bras)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "History Session on BRAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Session History ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sql.metrics.string.brasname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sql.metrics.numeric.usercount", "id": "1", "type": "max" }
     ],
     "query": "metricset.name: query sql.metrics.string.brasname = \"[[bras]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Concurrent Session Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Concurrent Session Detail",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "select conv(hex(Sbr_UniqueSessionId),16,10) as Sbr_UniqueSessionId,INET_NTOA(Sbr_Ipv4Address) as Sbr_Ipv4Address,Sbr_SessionState,${field:csv} from Sbr_CurrentSessions where Sbr_UserName in ($user) and Sbr_NasName in ($bras) limit $limit",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}