{
 "title": "Store Easy",
 "tags": [ "hardware" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"system.sysName.keyword\", \"query\":\"\"}"
   },
   {
    "name": "address",
    "label": "Address",
    "query": "{\"find\": \"terms\", \"field\": \"host_address.keyword\", \"query\":\"system.sysName.keyword: $hostname\"}"
   },
   {
    "name": "interface_name",
    "label": "Interface Name",
    "query": "{\"find\": \"fields\"}"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  float: right;\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/grafana/d/menu/menu?orgId=1', '_self')\"><span>BACK TO MENU</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Current Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Device Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "system.sysName: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last Data Received",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "system.sysName: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "host_address: \"[[address]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "host_address: \"[[address]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Devices Status",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "host_address: \"[[address]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.sysUpTimeInstance", "id": "1", "settings": { "script": "_value*10" }, "type": "max" }
     ],
     "query": "system.sysName: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.sysName",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "logs" },
      { "field": "system.hrSystemProcesses", "id": "2", "type": "max" }
     ],
     "query": "host_address: \"[[address]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "system.sysName: [[hostname]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "How to caculate ?",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "options": {
      "content": "\n`Storage Size`= ***StorageSize*** x ***AlocateUnit***\n\n`Storage Used`= ***StorageUsed*** x ***AlocateUnit***\n\n`Storage Available`=  `Storage Size` - `Storage Used`\n\n`Percentage`=  `Storage Used`/`Storage Size`x100"
     },
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Storage Desc",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 28 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
       ],
       "query": "system.sysName: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Storage Size",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 12, "w": 5, "x": 9, "y": 28 },
     "targets": [
      {
       "alias": "Size",
       "metrics": [
        { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
       ],
       "query": "system.sysName: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Storage Used",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 12, "w": 5, "x": 14, "y": 28 },
     "targets": [
      {
       "alias": "Size",
       "metrics": [
        { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
       ],
       "query": "system.sysName: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Alocation Unit",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 28 },
     "targets": [
      {
       "alias": "Size",
       "metrics": [
        { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
       ],
       "query": "system.sysName: [[hostname]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "interface_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth $interface_name",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "repeat": "interface_name",
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "4", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "interface.ifInOctets.[[interface_name]]",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "5",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "system.sysName: [[hostname]]",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "4", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "interface.ifOutOctets.[[interface_name]]",
         "hide": true,
         "id": "1",
         "type": "max"
        },
        {
         "field": "1",
         "hide": false,
         "id": "5",
         "pipelineAgg": "1",
         "type": "derivative"
        }
       ],
       "query": "host_address: \"[[address]]\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Installed Sofwares",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Installed Sofware",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
       ],
       "query": "host_address: \"[[address]]\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}