apiVersion: v1
kind: ConfigMap
metadata:
  name: vmware-cm
data:
  esx.yml: |
    default:
      vsphere_host: {{ .Values.vsphere.host }}
      vsphere_user: {{ .Values.vsphere.user | quote }}
      vsphere_password: {{ .Values.vsphere.password | quote }}
      ignore_ssl: True
      specs_size: 5000
      fetch_custom_attributes: True
      fetch_tags: True
      fetch_alarms: True
      collect_only:
          vms: True
          vmguests: True
          datastores: True
          hosts: True
          snapshots: True
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vmware-deployment
  name: exporter-vmware
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vmware-deployment
  template:
    metadata:
      labels:
        app: vmware-deployment
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: vmware-exporter
        args: ["-c", "/opt/esx/esx.yml"]
        volumeMounts:
        - name: vmware-volume
          mountPath: /opt/esx/esx.yml
          subPath: esx.yml
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 500m
            memory: 500Mi
      volumes:
        - name: vmware-volume
          configMap:
            name: vmware-cm
            items:
              - key: esx.yml
                path: esx.yml
---
apiVersion: v1
kind: Service
metadata:
  name: vmware
spec:
  selector:
    app: vmware-deployment
  ports:
    - name: vmware-port
      protocol: TCP
      port: 9272
      targetPort: 9272
  type: ClusterIP
