{
 "title": "Notifications History Log",
 "tags": [ "event_history" ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT DISTINCT name1 FROM icinga_objects WHERE objecttype_id=1 AND is_active=1"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "SELECT name2 FROM icinga_objects WHERE name1 in ($host) AND objecttype_id=2 AND is_active=1"
   },
   { "name": "limit", "label": "Limit", "query": "1000,10000,100000" }
  ]
 },
 "panels": [
  {
   "title": "Notifications - Host",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\r\n  n.start_time as Time,\r\n  oc.name1 as Contact,\r\n  oh.name1 as Host,\r\nCASE\r\n  WHEN n.notification_reason = 0 THEN\r\n  CASE\r\n      WHEN n.state = 0 THEN 'RECOVERY'\r\n      WHEN n.state = 1 THEN 'DOWN'\r\n      WHEN n.state = 2 THEN 'UNREACHABLE'\r\n      ELSE n.state\r\n  END\r\n  WHEN n.notification_reason = 1 THEN\r\n  CASE\r\n    WHEN n.state = 1 THEN 'ACKNOWLEDGEMENT (DOWN)'\r\n    WHEN n.state = 2 THEN 'ACKNOWLEDGEMENT (UNREACHABLE)'\r\n  END\r\n  WHEN n.notification_reason = 2 THEN\r\n  CASE\r\n    WHEN n.state = 0 THEN 'FLAPPINGSTART (UP)'\r\n    WHEN n.state = 1 THEN 'FLAPPINGSTART (DOWN)'\r\n    WHEN n.state = 2 THEN 'FLAPPINGSTART (UNREACHABLE)'\r\n  END\r\n  WHEN n.notification_reason = 3 THEN\r\n  CASE\r\n    WHEN n.state = 0 THEN 'FLAPPINGSTOP (UP)'\r\n    WHEN n.state = 1 THEN 'FLAPPINGSTOP (DOWN)'\r\n    WHEN n.state = 2 THEN 'FLAPPINGSTOP (UNREACHABLE)'\r\n  END\r\n  WHEN n.notification_reason = 5 THEN\r\n  CASE\r\n    WHEN n.state = 0 THEN 'DOWNTIMESTART (UP)'\r\n    WHEN n.state = 1 THEN 'DOWNTIMESTART (DOWN)'\r\n    WHEN n.state = 2 THEN 'DOWNTIMESTART (UNREACHABLE)'\r\n  END\r\n  WHEN n.notification_reason = 6 OR n.notification_reason = 7 THEN\r\n  CASE\r\n    WHEN n.state = 0 THEN 'DOWNTIMEEND (UP)'\r\n    WHEN n.state = 1 THEN 'DOWNTIMEEND (DOWN)'\r\n    WHEN n.state = 2 THEN 'DOWNTIMEEND (UNREACHABLE)'\r\n  END\r\n  WHEN n.notification_reason = 99 THEN\r\n  CASE\r\n    WHEN n.state = 0 THEN 'CUSTOM (UP)'\r\n    WHEN n.state = 1 THEN 'CUSTOM (DOWN)'\r\n    WHEN n.state = 2 THEN 'CUSTOM (UNREACHABLE)'\r\n  END\r\nEND AS Type,\r\n  occ.name1 AS Notification_Command,\r\n  n.output AS Infomation\r\n\r\nFROM\r\nicinga_contactnotifications c\r\nJOIN icinga_notifications n ON c.instance_id = n.instance_id AND c.notification_id = n.notification_id\r\nJOIN icinga_objects oc ON c.contact_object_id = oc.object_id\r\nJOIN icinga_objects oh ON n.object_id = oh.object_id\r\nLEFT JOIN icinga_contactnotificationmethods cn ON cn.contactnotification_id = c.contactnotification_id\r\nLEFT JOIN icinga_objects occ ON cn.command_object_id = occ.object_id\r\nWHERE UNIX_TIMESTAMP(n.start_time) BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND oh.objecttype_id = 1 AND oh.name1 in ($host)\r\nAND n.notification_id > ((select max(notification_id) from icinga_notifications) - $limit)\r\nORDER BY n.start_time desc;"
    }
   ]
  },
  {
   "title": "Notifications - Service",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\r\n  n.start_time AS Time,\r\n  oc.name1 AS Contact,\r\n  os.name1 as Host,\r\n  os.name2 as Service,\r\nCASE\r\n  WHEN n.notification_reason = 0 THEN \r\n  CASE \r\n    WHEN n.state = 0 THEN 'RECOVERY'\r\n    WHEN n.state = 1 THEN 'WARNING'\r\n    WHEN n.state = 2 THEN 'CRITICAL'\r\n    WHEN n.state = 3 THEN 'UNKNOWN'\r\n  END\r\n \r\n  WHEN n.notification_reason = 1 THEN \r\n  CASE \r\n    WHEN n.state = 1 THEN 'ACKNOWLEDGEMENT (WARNING)'\r\n    WHEN n.state = 2 THEN 'ACKNOWLEDGEMENT (CRITICAL)'\r\n    WHEN n.state = 3 THEN 'ACKNOWLEDGEMENT (UNKNOWN)'\r\n  END \r\n\r\n  WHEN n.notification_reason = 2 THEN \r\n  CASE \r\n    WHEN n.state = 0 THEN 'FLAPPINGSTART (OK)'\r\n    WHEN n.state = 1 THEN 'FLAPPINGSTART (WARNING)'\r\n    WHEN n.state = 2 THEN 'FLAPPINGSTART (CRITICAL)'\r\n    WHEN n.state = 3 THEN 'FLAPPINGSTART (UNKNOWN)'\r\n  END\r\n  \r\n    WHEN n.notification_reason = 3 THEN \r\n  CASE \r\n    WHEN n.state = 0 THEN 'FLAPPINGSTOP (OK)'\r\n    WHEN n.state = 1 THEN 'FLAPPINGSTOP (WARNING)'\r\n    WHEN n.state = 2 THEN 'FLAPPINGSTOP (CRITICAL)'\r\n    WHEN n.state = 3 THEN 'FLAPPINGSTOP (UNKNOWN)'\r\n  END\r\n  \r\n  WHEN n.notification_reason = 5 THEN \r\n  CASE \r\n    WHEN n.state = 0 THEN 'DOWNTIMESTART'\r\n    WHEN n.state = 1 THEN 'DOWNTIMESTART (WARNING)'\r\n    WHEN n.state = 2 THEN 'DOWNTIMESTART (CRITICAL)'\r\n    WHEN n.state = 3 THEN 'DOWNTIMESTART (UNKNOWN)'\r\n  END\r\n  \r\n    WHEN n.notification_reason = 6 OR n.notification_reason = 7 THEN\r\n  CASE \r\n    WHEN n.state = 0 THEN 'DOWNTIMEEND'\r\n    WHEN n.state = 1 THEN 'DOWNTIMEEND (WARNING)'\r\n    WHEN n.state = 2 THEN 'DOWNTIMEEND (CRITICAL)'\r\n    WHEN n.state = 3 THEN 'DOWNTIMEEND (UNKNOWN)'\r\n  END\r\n  \r\n    WHEN n.notification_reason = 99 THEN \r\n  CASE \r\n    WHEN n.state = 0 THEN 'CUSTOM (OK)'\r\n    WHEN n.state = 1 THEN 'CUSTOM (WARNING)'\r\n    WHEN n.state = 2 THEN 'CUSTOM (CRITICAL)'\r\n    WHEN n.state = 3 THEN 'CUSTOM (UNKNOWN)'\r\n  END\r\nEND AS Type,\r\n  occ.name1 AS Notification_Command,\r\n  n.output AS Infomation\r\nFROM  icinga_contactnotifications c\r\nJOIN icinga_notifications n ON c.instance_id = n.instance_id AND c.notification_id = n.notification_id\r\nJOIN icinga_objects oc ON c.contact_object_id = oc.object_id\r\nJOIN icinga_objects os ON n.object_id = os.object_id\r\nLEFT JOIN icinga_contactnotificationmethods cn ON cn.contactnotification_id = c.contactnotification_id\r\nLEFT JOIN icinga_objects occ ON cn.command_object_id = occ.object_id\r\nWHERE os.objecttype_id = 2 AND UNIX_TIMESTAMP(n.start_time) BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND os.name1 IN ($host) AND os.name2 IN ($service) \r\nAND n.notification_id > ((select max(notification_id) from icinga_notifications) - $limit)\r\nORDER BY n.start_time desc;"
    }
   ]
  },
  {
   "title": "Mail queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mailq",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}