---
- include: rhel_step01_iptables.yml

- include: rhel_step02_required_repo.yml

- include: rhel_step03_required_system_config.yml

- include: rhel_step04_install_docker.yml

- include: rhel_step05_install_kubernetes.yml

- include: rhel_step06_install_keepalived.yml
  when:
    - master_node_list|length > 1
    - master == True

- include: rhel_step07_install_haproxy.yml
  when:
    - master_node_list|length > 1
    - master == True

- include: rhel_step08_config_kubernetes_multi_master.yml
  when:
    - master_node_list|length > 1
    - master == True

- include: rhel_step08_config_kubernetes_single_master.yml
  when:
    - master_node_list|length == 1
    - master == True

- include: rhel_step09_config_kubernetes_worker.yml
  when:
    - master != True or master is not defined
