---
- name: Install Docker [Step 01] - Install Dependencies packages
  yum:
    name: ["yum-utils", "device-mapper-persistent-data", "lvm2", "bash-completion"]
    state: latest

- name: Install Docker [Step 02] - Install Docker
  yum:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]

- name: Install Docker [Step 03] - Docker bash completion
  copy:
    src: "{{ role_path }}/files/bash_completion/docker.sh"
    dest: "/etc/bash_completion.d/docker.sh"

- name: Install Docker [Step 04] - Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
