---
- name: REQUIRED CONFIG [Step 02] - Set modules-load
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    force: yes

- name: REQUIRED CONFIG [Step 02] - Set modprobe
  shell: "{{ item }}"
  with_items:
    - modprobe overlay
    - modprobe br_netfilter

- name: REQUIRED CONFIG [Step 03] - Set kubernetes-cri
  copy:
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    force: yes

- name: REQUIRED CONFIG [Step 04] - Disable swap
  shell: "{{ item }}"
  with_items:
    - swapoff -a
    - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

