---
- name: K8S - Single Master [STEP 01] - Init Kubernetes
  shell: "kubeadm init --pod-network-cidr {{ pod_subnet }} --service-cidr {{ service_subnet }}"

- name: K8S - Single Master [STEP 02] - Set up kubectl access
  shell: "{{ item }}"
  with_items:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config

- name: K8S - Single Master [STEP 03] - Install network add-on - weave
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when:
    - cni == weave

- name: K8S - Single Master [STEP 18] - Install network add-on - calico
  shell: kubectl apply -f "https://docs.projectcalico.org/manifests/calico.yaml"
  when:
    - cni == calico

- name: K8S - Single Master [STEP 04] - Install Auto complete
  shell: echo "source <(kubectl completion bash)" > /etc/bash_completion.d/kubernetes.sh

- name: K8S - Multi Master [STEP 05] - Create token and join command
  shell: kubeadm token create --print-join-command
  register: get_join_command

- name: Create join_command var
  set_fact:
    join_command: "{{ get_join_command.stdout }}"
  delegate_to: localhost
  run_once: yes

- name: debug
  debug:
    msg: "{{ join_command }}"
