---
  - name: IPTABLES [Step 01] - Stop Firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no
    ignore_errors: yes

  - name: IPTABLES [Step 02] - Install Iptables
    yum:
      name: "{{ item.service }}"
      state: latest
    with_items:
      - { service: "iptables" }
      - { service: "iptables-services" }

  - name: IPTABLES [Step 02] - Add Ports to Iptables
    blockinfile:
      dest: /etc/sysconfig/iptables
      insertafter: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
      state: present
      backup: yes
      marker: '# {mark} ANSIBLE MANAGED BLOCK - K8S'
      content: |
        -A INPUT -s {{ VIP }} -j ACCEPT
        -A INPUT -s {{ pod_subnet }} -j ACCEPT
        -A INPUT -s {{ service_subnet }} -j ACCEPT
        {% for item in hostvars.values() %}
        -A INPUT -s {{ item["IP"] }} -j ACCEPT
        {% endfor %}

  - name: IPTABLES [Step 03] - Start Iptables
    service:
      name: iptables
      state: restarted
      enabled: yes
