{
 "title": "01 - VM - Detail Information",
 "tags": [ "Metric" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\", \"query\":\"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  float: right;\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/grafana/d/menu/menu?orgId=1', '_self')\"><span>BACK TO MENU</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Current Host's Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "OS Infformation",
   "type": "table",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 4 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "host.name:[[hostname]] AND host.ip:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " IP Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "host.name:[[hostname]] AND host.ip:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last Data Received",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage Gauge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.cpu.total.norm.pct", "id": "1", "type": "max" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Load Gauge (5m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "4", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.load.5", "id": "1", "type": "avg" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage Gauge",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "6", "settings": { "interval": "5m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.memory.actual.used.pct", "id": "1", "type": "max" },
      { "field": "system.memory.swap.used.pct", "id": "5", "type": "max" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage ",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.filesystem.mount_point",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "system.filesystem.used.pct", "id": "1", "type": "max" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "system.uptime.duration.ms", "id": "1", "type": "avg" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Inbound traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "settings": { "script": "_value / 10" },
       "type": "max"
      },
      {
       "field": "1",
       "hide": false,
       "id": "4",
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.name: \"[[hostname]]\" AND -system.network.name:l*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Inbound traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "1",
       "settings": { "script": "_value / 10" },
       "type": "max"
      },
      {
       "field": "1",
       "hide": false,
       "id": "4",
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.name: \"[[hostname]]\" AND -system.network.name:l*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Packetloss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.dropped",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "max"
      },
      { "field": "system.network.out.dropped", "id": "6", "type": "max" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Tables Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Process by Memory",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "process.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "system.process.memory.rss.pct",
       "hide": false,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Process by CPU",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "process.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "system.process.cpu.total.pct", "id": "1", "type": "avg" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Interfaces Traffic",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.network.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "id": "1",
       "settings": {},
       "type": "max"
      },
      { "field": "system.network.out.bytes", "id": "3", "type": "max" }
     ],
     "query": "host.name: \"[[hostname]]\" AND -system.network.name:l*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Historical Performance Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.cpu.user.pct", "id": "1", "type": "avg" },
      { "field": "system.cpu.system.pct", "id": "4", "type": "avg" },
      { "field": "system.cpu.nice.pct", "id": "5", "type": "avg" },
      { "field": "system.cpu.irq.pct", "id": "6", "type": "avg" },
      { "field": "system.cpu.softirq.pct", "id": "7", "type": "avg" },
      { "field": "system.cpu.iowait.pct", "id": "8", "type": "avg" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.used.bytes",
       "hide": true,
       "id": "3",
       "type": "avg"
      },
      {
       "field": "system.memory.actual.used.bytes",
       "id": "5",
       "type": "avg"
      },
      {
       "id": "6",
       "pipelineVariables": [
        { "name": "actual", "pipelineAgg": "5" },
        { "name": "used", "pipelineAgg": "3" }
       ],
       "settings": {
        "script": "params.actual != null && params.used != null ? params.used - params.actual : null"
       },
       "type": "bucket_script"
      },
      { "field": "system.memory.free", "id": "7", "type": "avg" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.load.1",
       "id": "1",
       "settings": {},
       "type": "avg"
      },
      { "field": "system.load.5", "id": "4", "type": "avg" },
      { "field": "system.load.15", "id": "5", "type": "avg" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk IO (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "1m", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.diskio.read.bytes",
       "hide": true,
       "id": "1",
       "settings": { "script": "_value / 10" },
       "type": "max"
      },
      {
       "field": "1",
       "id": "6",
       "pipelineAgg": "1",
       "settings": { "unit": "10s" },
       "type": "derivative"
      },
      {
       "field": "system.diskio.write.bytes",
       "hide": true,
       "id": "7",
       "settings": { "script": "_value / 10" },
       "type": "max"
      },
      {
       "field": "7",
       "hide": false,
       "id": "8",
       "pipelineAgg": "7",
       "settings": { "unit": "10s" },
       "type": "derivative"
      }
     ],
     "query": "host.name: \"[[hostname]]\" AND -system.network.name:l*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Interfaces In Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "5", "settings": { "interval": "1m", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "settings": { "script": "_value / 10" },
       "type": "max"
      },
      {
       "field": "1",
       "hide": false,
       "id": "4",
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.name: \"[[hostname]]\" AND -system.network.name:l*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Interfaces Out Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "5", "settings": { "interval": "1m", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "1",
       "settings": { "script": "_value / 10" },
       "type": "max"
      },
      {
       "field": "1",
       "hide": false,
       "id": "4",
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "host.name: \"[[hostname]]\" AND -system.network.name:l*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Process by Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "process.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.process.memory.rss.pct", "id": "1", "type": "avg" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Process by CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "process.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.process.cpu.total.pct", "id": "1", "type": "avg" }
     ],
     "query": "host.name: \"[[hostname]]\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}