{
 "title": "Access Log Detail",
 "tags": [ "junos-log" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter", "label": "ES Filter " },
   {
    "name": "device",
    "label": "Device ",
    "query": "{\"find\": \"terms\", \"field\": \"junos_hostname.keyword\", \"query\": \"login_protocol:[[login_protocol]] AND tags:login_trigger AND NOT login_session.keyword:junos_script AND NOT [[ignore_user]]\"}"
   },
   { "name": "ignore_user", "label": "ignore_user", "query": "login.user:(icinga OR nims)" },
   {
    "name": "ignore_login_source",
    "label": "ignore_login_source",
    "query": "login_source:(10.229.17.31 OR 10.229.17.19)"
   },
   {
    "name": "login_protocol",
    "label": "Login Protocol",
    "query": "{\"find\": \"terms\", \"field\": \"login_protocol.keyword\", \"query\": \"NOT login_protocol.keyword:junoscript\"}"
   },
   {
    "name": "SID",
    "label": "Session ID",
    "query": "{\"find\": \"terms\", \"field\": \"login_session.keyword\", \"query\": \"login_protocol:[[login_protocol]] AND tags:login_trigger AND NOT [[ignore_login_session]] AND NOT [[ignore_user]]\"}"
   },
   {
    "name": "ignore_login_session",
    "label": "ignore_login_session",
    "query": "login_session.keyword:(junoscript OR pending)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Commands of Session",
   "type": "stat",
   "description": "Number of Command was Executed within the Time Range",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:35",
       "fake": true,
       "field": "junos_command.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:33", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "junos_command:* AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SHOW",
   "type": "stat",
   "description": "Number of SHOW Command was Executed within the Time Range",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "junos_command:(\"show*\" OR \"run show*\") AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SET",
   "type": "stat",
   "description": "Number of SET Command was Executed within the Time Range",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "junos_command.keyword:set* AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DELETE",
   "type": "stat",
   "description": "Number of COMMIT Command was Executed within the Time Range",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "junos_command.keyword:delete* AND NOT junos_command.keyword:*check* AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "COMMIT",
   "type": "stat",
   "description": "Number of COMMIT Command was Executed within the Time Range",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:488",
       "fake": true,
       "field": "junos_command.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:486", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "junos_command.keyword:commit* AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Other Commands",
   "type": "stat",
   "description": "Number of Other Command was Executed within the Time Range",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:470",
       "fake": true,
       "field": "junos_command.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:468", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "NOT junos_command:(\"show*\" OR \"run show*\" OR \"set*\" OR \"commit*\" OR \"delete*\") AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SHOW Timeline (Count)",
   "type": "graph",
   "description": "The Number of SET Command were executed on All Devices within the Time Range",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Number of Commands" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "junos_command.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "junos_command:(\"show*\" OR \"run show*\") AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SET Timeline (Count)",
   "type": "graph",
   "description": "The Number of SET Command were executed on All Devices within the Time Range",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Number of Commands" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "junos_command.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "junos_command.keyword:set* AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DELETE Timeline (Count)",
   "type": "graph",
   "description": "The Number of Commit Command were executed on All Devices within the Time Range",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Number of Commands" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "junos_command.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "junos_command.keyword:delete* AND NOT junos_command.keyword:*check* AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "COMMIT Timeline (Count)",
   "type": "graph",
   "description": "The Number of Commit Command were executed on All Devices within the Time Range",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Number of Commands" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "junos_command.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "junos_command.keyword:commit* AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Users's Access Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Users's Access Information",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:234",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "tags: login_trigger AND login_protocol.keyword:[[login_protocol]] AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Users's Executed Commands",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:42",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:40",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "junos_command:* AND junos_hostname.keyword:[[device]] AND login_session.keyword:[[SID]]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}