{
 "title": "Juniper - Access Log Ovierview",
 "tags": [
  "Log",
  "Juniper"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "filter", "label": "ES Filter " },
   {
    "name": "device",
    "label": "Device ",
    "query": "{\"find\": \"terms\", \"field\": \"junos_hostname.keyword\", \"query\": \"login_protocol:[[login_protocol]] AND tags:login_trigger AND NOT login_session.keyword:junos_script AND NOT [[ignore_user]]\"}"
   },
   { "name": "ignore_user", "label": "ignore_user", "query": "login.user:(icinga OR nims)" },
   {
    "name": "ignore_login_source",
    "label": "ignore_login_source",
    "query": "login_source:(10.229.17.31 OR 10.229.17.19)"
   },
   {
    "name": "login_protocol",
    "label": "Login Protocol",
    "query": "{\"find\": \"terms\", \"field\": \"login_protocol.keyword\", \"query\": \"NOT login_protocol.keyword:junoscript\"}"
   }
  ]
 },
 "panels": [
  { "title": "Access Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Connections",
   "type": "stat",
   "description": "Total Connections of SSH, Telnet, Netconf within selected Time Range ",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:364",
       "fake": true,
       "field": "login_protocol.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:362", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(login_protocol.keyword:[[login_protocol]] AND junos_hostname.keyword:[[device]] AND tags.keyword:(\"login_trigger\")) AND NOT login_protocol.keyword:(\"junoscript\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3102",
       "field": "junos_hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3118",
       "field": "junos_hostname.keyword",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Access Login Overview Pie Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "login_protocol.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(login_protocol.keyword:[[login_protocol]] AND junos_hostname.keyword:[[device]] AND tags.keyword:(\"login_trigger\")) AND NOT login_protocol.keyword:(\"junoscript\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Classification of Authentication Protocols",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:222",
       "fake": true,
       "field": "login_protocol.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:223",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:220", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "junos_hostname.keyword:[[device]] AND tags.keyword: login_trigger AND login_protocol.keyword:[[login_protocol]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Commands",
   "type": "stat",
   "description": "Number of Commands were Executed within the Time Range",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "fake": true,
       "field": "junos_command.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "junos_command: * AND junos_hostname.keyword:[[device]]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Access Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Device Login Timeline",
   "type": "graph",
   "description": "Show the Devices's access information (host, where)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Number of Commands" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:68",
       "fake": true,
       "field": "junos_hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:69",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:66",
       "field": "junos_command.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "tags:login_trigger AND login_protocol.keyword:[[login_protocol]] AND junos_hostname.keyword:[[device]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Commands Timeline (Count)",
   "type": "graph",
   "description": "The Number of Command were executed on All Devices within the Time Range",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of Commands" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:284",
       "fake": true,
       "field": "junos_command.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:285",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:282",
       "field": "junos_command.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "junos_command.keyword:* AND junos_hostname.keyword:[[device]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SET Timeline (Count)",
   "type": "graph",
   "description": "The Number of SET Command were executed on All Devices within the Time Range",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Number of Commands" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "junos_command.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "junos_command.keyword:set* AND junos_hostname.keyword:[[device]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DELETE Timeline (Count)",
   "type": "graph",
   "description": "The Number of Commit Command were executed on All Devices within the Time Range",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Number of Commands" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "junos_command.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "junos_command.keyword:delete* AND NOT junos_command.keyword:*check* AND junos_hostname.keyword:[[device]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "COMMIT Timeline (Count)",
   "type": "graph",
   "description": "The Number of Commit Command were executed on All Devices within the Time Range",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Number of Commands" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "junos_command.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "junos_command.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "junos_command.keyword:commit* AND NOT junos_command.keyword:*check* AND junos_hostname.keyword:[[device]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Users's Access Information",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "tags: login_trigger AND login_protocol.keyword:[[login_protocol]] AND junos_hostname.keyword:[[device]]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}