apiVersion: v1
kind: ConfigMap
metadata:
  name: pnetlab-cm
data:
  config.yaml: |
    databases:
      {{ range .Values.databases }}
      {{ .host }}:
        dsn:
          dialect: mysql
          user: {{ .user }}
          password: {{ .password }}
          host: {{ .host }}
          port: {{ .port }}
          database: pnetlab_db
      {{ end }}
    metrics:
      node_cpu:
        type: gauge
        description: CPU usage of nodes in lab
        labels:
          - node_port
          - node_id
          - lab_id
          - lab_path
      node_memory:
        type: gauge
        description: Memory usage of nodes in lab
        labels:
          - node_port
          - node_id
          - lab_id
          - lab_path
      node_used_space:
        type: gauge
        description: Used space of nodes in lab
        labels:
          - node_port
          - node_id
          - lab_id
          - lab_path
      node_running:
        type: gauge
        description: Running state of nodes in lab
        labels:
          - node_port
          - node_id
          - lab_id
          - lab_path
    queries:
      query1:
        interval: {{ .Values.interval }}
        databases: [{{ include "joinList" ( dict "arr" .Values.databases ) }}]
        metrics: [node_running]
        sql: SELECT a.node_session_running as node_running  , b.lab_session_path as lab_path, a.node_session_port as node_port, a.node_session_lab as lab_id, a.node_session_nid as node_id from node_sessions as a inner join lab_sessions as b on a.node_session_lab = b.lab_session_id
      query2:
        interval: {{ .Values.interval }}
        databases: [{{ include "joinList" ( dict "arr" .Values.databases ) }}]
        metrics: [node_cpu]
        sql: SELECT a.node_session_cpu as node_cpu , b.lab_session_path as lab_path, a.node_session_port as node_port, a.node_session_lab as lab_id, a.node_session_nid as node_id from node_sessions as a inner join lab_sessions as b on a.node_session_lab = b.lab_session_id
      query3:
        interval: {{ .Values.interval }}
        databases: [{{ include "joinList" ( dict "arr" .Values.databases ) }}]
        metrics: [node_memory]
        sql: SELECT a.node_session_ram as node_memory , b.lab_session_path as lab_path, a.node_session_port as node_port, a.node_session_lab as lab_id, a.node_session_nid as node_id from node_sessions as a inner join lab_sessions as b on a.node_session_lab = b.lab_session_id
      query4:
        interval: {{ .Values.interval }}
        databases: [{{ include "joinList" ( dict "arr" .Values.databases ) }}]
        metrics: [node_used_space]
        sql: SELECT a.node_session_hdd as node_used_space , b.lab_session_path as lab_path, a.node_session_port as node_port, a.node_session_lab as lab_id, a.node_session_nid as node_id from node_sessions as a inner join lab_sessions as b on a.node_session_lab = b.lab_session_id
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pnetlab-deployment
  name: exporter-pnetlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pnetlab-deployment
  template:
    metadata:
      labels:
        app: pnetlab-deployment
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: pnetlab-exporter
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: pnetlab-volume
          mountPath: /config.yaml
          subPath: config.yaml
      volumes:
        - name: pnetlab-volume
          configMap:
            name: pnetlab-cm
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: pnetlab
spec:
  selector:
    app: pnetlab-deployment
  ports:
    - name: pnetlab-port
      protocol: TCP
      port: 9560
      targetPort: 9560
  type: ClusterIP
