apiVersion: v1
kind: ConfigMap
metadata:
  name: pve-cm
data:
  pve.yml: |
    default:
      user: {{ .Values.user }}
      password: {{ .Values.password }}
      verify_ssl: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pve-deployment
  name: exporter-pve
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pve-deployment
  template:
    metadata:
      labels:
        app: pve-deployment
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: prometheus-pve-exporter
        volumeMounts:
        - name: pve-volume
          mountPath: /etc/pve.yml
          subPath: pve.yml
      volumes:
        - name: pve-volume
          configMap:
            name: pve-cm
            items:
              - key: pve.yml
                path: pve.yml
---
apiVersion: v1
kind: Service
metadata:
  name: pve
spec:
  selector:
    app: pve-deployment
  ports:
    - name: pve-port
      protocol: TCP
      port: 9221
      targetPort: 9221
  type: ClusterIP
