{
 "title": "02 - Fortigate - Syslog",
 "tags": [
  "Log",
  "Hardware-Log"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"observer.name\", \"query\":\"\"}"
   },
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "{\"find\": \"terms\", \"field\": \"log.level\", \"query\":\"observer.name:[[hostname]]\"}"
   },
   {
    "name": "src_ip",
    "label": "Source IP",
    "query": "{\"find\": \"terms\", \"field\": \"source.ip\", \"query\":\"observer.name:[[hostname]] and log.level:[[log_level]]\"}"
   },
   {
    "name": "dst_ip",
    "label": "Destination IP",
    "query": "{\"find\": \"terms\", \"field\": \"destination.ip\", \"query\":\"observer.name:[[hostname]] and log.level:[[log_level]]\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Data Received",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "query": "observer.name: \"[[hostname]]\" OR not observer.name:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  float: right;\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: white;\n  color: grey;\n  border:1px solid grey;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('/grafana/d/menu/menu?orgId=1', '_self')\"><span>BACK TO MENU</span></button>\n\n</body>\n</html>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Syslog Overview Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Logs by Host Over Time (Log Level: [[log_level]])",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "observer.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "observer.name: [[hostname]] AND log.level: [[log_level]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Syslog Logs by Hosts (Log Level: [[log_level]])",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "observer.name",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "observer.name: [[hostname]] AND log.level: [[log_level]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Syslog Logs by Seveirty (Log Level: [[log_level]])",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "log.level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "observer.name: [[hostname]] AND log.level: [[log_level]]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Syslog by Source IP: <[[src_ip]]>",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syslog Logs by Source IP (Log Level: [[log_level]])",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "source.ip",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "observer.name: [[hostname]] AND source.ip: [[src_ip]] AND log.level: [[log_level]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Syslog from <[[src_ip]]> (Source IP) to Destination IP (Log Level: [[log_level]])",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "destination.ip",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "observer.name: [[hostname]] AND source.ip: [[src_ip]] AND log.level: [[log_level]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Syslog by Destination IP <[[dst_ip]]>",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syslog Logs by Destination IP (Log Level: [[log_level]])",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "destination.ip",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "observer.name: [[hostname]] AND destination.ip: [[dst_ip]] AND log.level: [[log_level]]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Syslog from Source IP to <[[dst_ip]]> (Log Level: [[log_level]])",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "source.ip",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "observer.name: [[hostname]] AND destination.ip: [[dst_ip]] AND log.level: [[log_level]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": " ",
     "type": "briangann-datatable-panel",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "observer.name: [[hostname]] AND log.level: [[log_level]]",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}